### ISSUE TITLE
[Bug]: KeyError: 'meta'

### ISSUE THREAD

**Issue by DEX-1101** [BlafKing/sd-civitai-browser-plus#220] opened 2024-03-06 06:19 UTC
### Describe the bug.

i just encountering the error today when trying to download a model.
![Screenshot_56](https://github.com/BlafKing/sd-civitai-browser-plus/assets/71503763/4a263bac-0187-481c-a948-62cf4762fe3c)
![Screenshot_55](https://github.com/BlafKing/sd-civitai-browser-plus/assets/71503763/f108797d-5fe2-43c5-a162-a76b9468d8a6)

### Steps to reproduce the problem.

1. Go to CivitAI Browser Plus tab
2. Search model and click the model
3. and then error pop up.

### Expected behavior

clicking the model and it should appear the info.

### System info

* Extension version: latest commit 177ce5d1
* OS: Kaggle Jupyter
* SD-WebUI version: 1.8.0
* Python: python: 3.10.13 

### Console logs

```Shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/kaggle/working/x1101/extensions/sd-civitai-browser-plus/scripts/civitai_gui.py", line 372, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "/kaggle/working/x1101/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 744, in update_model_info
    meta = pic['meta']
KeyError: 'meta'
```

**Comment by BlafKing** [comment] 2024-03-11 00:10
Thanks for reporting.

It looks like you're not using the latest version, as this issue should already be fixed in later commits.
This issue is a duplicate of #210 

If you update to the latest version, the issue should be solved! :)

**Closed by BlafKing** 2024-03-11 00:10 UTC
Labels: bug

**Comment by DEX-1101** [comment] 2024-03-11 01:48
thankyou for pointing the issue, i just recheck again, i already use the latest commit, the webui show it but when i check the files apparently the files are not updated. it fixed now
