### ISSUE TITLE
[BUG] Certain search words trigger errors on specific searches. 

### ISSUE THREAD

**Issue by gurukast** [BlafKing/sd-civitai-browser-plus#51] opened 2023-09-28 23:36 UTC
Certain words produce an error when conducting specific types of searches.  They have a few that do it, but this is the only i really took notice off because I thought it was just network connection errors before. 

**To Reproduce**
**Steps to reproduce the behavior:**
- Start a brand new fresh session/tab.
- leave content type blank, set sort type to newest
- Set search term to Next
- Click Refresh.
- errors out the UI

**Notes/ Observations:** 
- Selecting any other [sort by] option functions as normal
- Selecting any/all [Content type] functions as normal
- if you do a blank [content type] with another [sort by], and then switch to [Newest], it errors out, but clicking [next page] works as expected.  Clicking [previous page] from that page, however, results in an error, so its something about that first page result.

**Additional context**
* Extension version: 0f26dcb8	2023-09-28 15:16:20 v1.12.5 (Hotfix)
* OS: Windows
version: v1.6.0  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

**Comment by BlafKing** [comment] 2023-09-29 00:49
Thanks for notifying me about the issue!

The issue is caused by content type's that the current folder selection function is not accounting for, since they previously weren't supported by the public API.

It turns out that the punlic CivitAI API docs are fairly outdated, it looks it already supports more content type's than what they are listing in the API docs, `Upscaler, MotionModule, Wildcards, Workflows and Other` seem to be supported but unlisted!

I'll start on implementing the 'new' content types, the extension will then also be able to search for these and this should also fix the error! :)

**Comment by gurukast** [comment] 2023-09-29 02:55
Your response rate and update rate are ridiculous. You spoil us!

**Comment by BlafKing** [comment] 2023-09-29 04:21
Thanks for the kind words! :)

This bug should now be fixed in v1.13, took a bit long to implement since I had to figure out how to properly point to all the correct folders for the new content types + I also added in support for video's instead of only images and found some other bugs while fixing this one :)

I'll close this thread now since the bug should be fixed!

**Closed by BlafKing** 2023-09-29 04:21 UTC
Labels: bug, WIP
