### ISSUE TITLE
[Bug] Invalid version: '.7.0'

### ISSUE THREAD

**Issue by Ptibouc77** [BlafKing/sd-civitai-browser-plus#165] opened 2024-01-12 16:12 UTC
### Describe the bug.

I updated my DirectML automatic1111 and this extension and now i have this error:

### Console logs

```Shell
CivitAI Browser+: Aria2 RPC started
fatal: No names found, cannot describe anything.
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "C:\amd_sd\stable-diffusion-webui-directml\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\amd_sd\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 35, in <module>
        ver_bool = version.parse(ver[1:]) >= version.parse("1.7")
      File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\packaging\version.py", line 54, in parse
        return Version(version)
      File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\packaging\version.py", line 200, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    packaging.version.InvalidVersion: Invalid version: '.7.0'
```

### Expected behavior

It look like it returns version:'.7.0'  instead of version:'1.7.0'
I tried to delete the venv folder and did a clean install of Browser+ without any change

### System info

* Extension version: Latest
* OS: Windows 11
* SD-WebUI version: [1.7.0](https://github.com/lshqqytiger/stable-diffusion-webui-directml)
* Python:3.11.4

**Comment by dimitri-weidriti** [comment] 2024-01-13 00:24
Im having the same problem. 

CivitAI Browser+: Aria2 RPC started
fatal: not a git repository (or any of the parent directories): .git
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "C:\Users\bruno\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\bruno\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\bruno\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 35, in <module>
        ver_bool = version.parse(ver[1:]) >= version.parse("1.7")
      File "C:\Users\bruno\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 54, in parse
        return Version(version)
      File "C:\Users\bruno\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 200, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    packaging.version.InvalidVersion: Invalid version: '.7.0'

**Comment by BlafKing** [comment] 2024-01-13 00:30
Thanks for reporting!

This issue is caused by the latest commit which attempts to fix another issue with some people their SD-WebUI versions,
Could any of you please do the following?

Open the civitai_gui.py file, usually it's in `webui/extensions/sd-civitai-browser-plus/scripts/civitai_gui.py`
Then please add a new line below line 33, and add `print(f"initial ver: {ver}")` to this line

So then the code would be:
```
    if ver:
        print(f"initial ver: {ver}")
```

This should print the initial version before the error occurs, which would help me to debug this issue! :)

**Comment by ComGreed** [comment] 2024-01-13 01:02
CivitAI Browser+: initial ver: 1.7.0

**Comment by BlafKing** [comment] 2024-01-13 05:33
Thanks for the info!

I assumed I had to remove the "v" in front of the version for the version checking to work properly, (since it prints `v1.7.0` for me)
But it looks like it works regardless of the v being present, so that fix is perfect!

I've now included this in the latest version so this issue is now fixed! :)

**Closed by BlafKing** 2024-01-13 05:33 UTC
Labels: bug
