### ISSUE TITLE
[Bug]: Weird Missing Models

### ISSUE THREAD

**Issue by Worldgate** [BlafKing/sd-civitai-browser-plus#134] opened 2023-12-13 14:29 UTC
### Describe the bug.

So when I import the models and then display them in the browser this one model shows only 1 of 2 available.  Not sure why this one is bugged, not even sure if its a problem with the extension or with civitai.  Webpage shows 2 models, bit the browser shows only 1.

https://civitai.com/models/21503

I have the older of the two downloaded, but doesn't show up in the browser, but does scrape the sha and the model number from the website.

### Steps to reproduce the problem.

1. Go to .... 
2. Press ....
3. ...

### Expected behavior

To display both models in the drop down.

### System info

* Extension version: Latest as of today
* OS: Win 10
* SD-WebUI version: Current
* Python: Version suggested by automatic 1111

### Console logs

```Shell
venv "H:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access --ckpt-dir Y:\CKPT
CivitAI Browser+: Aria2 RPC started
Checkpoint yiffymix_v36-2.0GB-ST\yiffymix_v36.safetensors [fb27ebf750] not found; loading fallback 2mix3Sakura_v10Sakura\2mix3Sakura_v10Sakura.safetensors
Calculating sha256 for Y:\CKPT\2mix3Sakura_v10Sakura\2mix3Sakura_v10Sakura.safetensors: Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.6s (prepare environment: 4.4s, import torch: 5.9s, import gradio: 1.8s, setup paths: 1.5s, initialize shared: 0.4s, other imports: 1.0s, setup codeformer: 0.2s, list SD models: 0.6s, load scripts: 2.3s, create ui: 1.1s, gradio launch: 4.5s).
795683c691b6375c4c0d5774484d252c8820e6d8e24fdb0e59eab25c7b8fbabd
Loading weights [795683c691] from Y:\CKPT\2mix3Sakura_v10Sakura\2mix3Sakura_v10Sakura.safetensors
Creating model from config: H:\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 30.7s (calculate hash: 20.3s, load weights from disk: 0.3s, create model: 1.5s, apply weights to model: 7.8s, apply half(): 0.2s, load VAE: 0.2s, calculate empty prompt: 0.2s).
```

**Comment by BlafKing** [comment] 2023-12-14 04:16
Thanks for reporting!

This issue was caused by a silly oversight I made in the early access detection code, every model that was once in early access was hidden which caused the version to not display.

This is now fixed in the latest version! :)

**Closed by BlafKing** 2023-12-14 04:16 UTC
Labels: bug
