### ISSUE TITLE
Can't jump to other pages

### ISSUE THREAD

**Issue by TypicaIDay** [BlafKing/sd-civitai-browser-plus#238] opened 2024-03-18 21:43 UTC
### Describe the bug.

I cannot jump to other pages, say for example I wanted to jump to page 26, whenever I put 26 in the page number, it doesn't put me there.

### Steps to reproduce the problem.

1. Go to CivitAI Browser section
2. Press the search bar to show results
3. Put in number 26 in the page number

### Expected behavior

I expected it to just jump to said page.

### System info

* Extension version: latest
* OS: Windows 11
* SD-WebUI version: v1.8.0
* Python: 3.10.6

### Console logs

```Shell
None
```

**Comment by BlafKing** [comment] 2024-03-18 21:52
This is no longer possible since the CivitAI API update.
The paging system returned by the API now works with a "cursor" based paging system.
Before the update it was possible to simply define which page you would like to get returned and access it, but now, the API no longer accepts a page number, it simply only returns a URL for the next page.

So in other words, it's only possible to jump to pages that you've already visited, until you do a new search, then the page index resets.

This extension saves all the URLs that you have visited, so that you are able to go back to a previous page, and so that you jump to previous pages, but it's not possible to know what the URL for an arbitrary page number would be, unless already visited through clicking "Next page".

This change was unfortunately required because of the number of models now hosted on CivitAI.
Indexing all the pages for each request took too much processing power, which is why a cursor based system is now used.

I'll close this bug report as it's not a bug, but intended behaviour with the new CivitAI API.

**Closed by BlafKing** 2024-03-18 21:52 UTC
Labels: bug
