### ISSUE TITLE
[Bug]: Missing models

### ISSUE THREAD

**Issue by Walkyst** [BlafKing/sd-civitai-browser-plus#154] opened 2024-01-03 21:16 UTC
### Describe the bug.

There are missing models

https://civitai.com/models/194771 missing v2.0
https://civitai.com/models/194743 missing v2.0
https://civitai.com/models/207864 not missing v2.0
https://civitai.com/models/194794 missing v2.0
https://civitai.com/models/200230 missing v2.0

Just found that maybe 'Kawaii' have all versions because it's not NSFW? All other marked as NSFW and don't have v2.0 but on site it is

### Steps to reproduce the problem.

1. Go to Civitai Browser+
2. Press search bar and type 'one for all'
3. All models will be here but missing v2.0 versions except 'Kawaii'

### Expected behavior

All versions should be here they can be accessed from site but not from extension

### System info

* Extension version: Latest v.3.2.1 commit [988b57c5](https://github.com/BlafKing/sd-civitai-browser-plus/commit/988b57c57d879b229d80402900743e8d3830f456)
* OS: Windows 11
* SD-WebUI version: [v1.6.0-261-g861cbd56](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/861cbd56363ffa0df3351cf1162f507425a178cd)
* Python: 3.10.6

### Console logs

```Shell
There no errors or logs from extension only this on start

CivitAI Browser+: Aria2 RPC started
CivitAI Browser+: Python module 'packaging' has not been imported correctly, please try to restart or install it manually.
(Also would like to know why extension not installing 'packaging' module by itself or I'm doing something wrong here)
```

**Comment by BlafKing** [comment] 2024-01-06 18:02
Thanks for reporting!

Unfortunately the issue regarding models not showing up is caused by the CivitAI API, so there isn't much that I can do to fix it.

It's hidden because it detects the version as being in early access, which is based on the (in this case incorrect) API return.
This is the relevant part of the API response for the v2.0 version of the 194743 model for example:
```
publishedAt: "2024-01-01T23:24:00.000Z"
earlyAccessTimeFrame: 5
```

The `earlyAccessTimeFrame` indicates how many days a model will be in early access, the extension then adds the amount of days found there to the `publishedAt` date, to get the final date of when the model will be available.\
It looks like API returns an incorrect `publishedAt` date causing the extension to think that the version is still in early access.
If you'd like, you can turn off early access models being hidden in the settings tab under CivitAI Browser+.

(The CivitAI site uses a private API, which is why this issue doesn't show up on the site.)

About your other issue where the `packaging` is not being installed, I'm not sure why that occurs, it's listed in the `install.py` file of the extension, which gets used by SD-WebUI to automatically install the package before starting, so it should get installed automatically as long as you're not using the `--skip-install` command line argument/flag.

You can try manually installing it by finding your python executable which is used for SD-WebUI and running the following command:
`python -m pip install packaging`

(usually the python location is next to the webui folder, in `system\python\python.exe`)

Sorry for the wall of text, and thanks for reporting regardless!
I'll close this bug report since there unfortunately isn't much I can do about this issue :,)

**Closed by BlafKing** 2024-01-06 18:02 UTC
Labels: bug
