### ISSUE TITLE
[Bug]: Error when checking for LoCon updates in Update Models Tab

### ISSUE THREAD

**Issue by AbsolomTDaak** [BlafKing/sd-civitai-browser-plus#83] opened 2023-10-23 13:33 UTC
### Describe the bug.

While trying to check for any updates to Locon in the update tab, I get error message as seen in images.
Did fresh install, of everything... Python, Git, Stability Matrix and Stable Diffusion and only added this extension and controlnet and reactor.   The terminal in Stability Matrix (which is just a front end for installing various UI) shows the following in the terminal screen

![StabilityMatrix_yFzn7IQGR7](https://github.com/BlafKing/sd-civitai-browser-plus/assets/68911924/205f5539-d623-459d-995c-3352e61db4e4)

 and in automatic1111 it shows

![firefox_zSsJoswGZx](https://github.com/BlafKing/sd-civitai-browser-plus/assets/68911924/c89a4f82-91e9-4850-bc88-f5964669d125)

Apart from the locon part, everything else is working correctly with just those three extensions.  Have tried it with just this extension installed and get the same problem.  

Have tried it without any LyCoris in directory, just one single Lycoris in directory, one sub-directory (many lycoris) and two sub-directories (with many LyCoris in them), and still get same error. 

Also noticed that when doing scan for latest releases in Browser when choosing LoCon in it also produces this error, seen in screenshot

![firefox_JI352CdsbV](https://github.com/BlafKing/sd-civitai-browser-plus/assets/68911924/74038ded-66ba-4018-b874-7380885d3f4c)

same terminal message as before.

looks like it will be a simple fix to set the namespace attribute.

Any ideas how to fix this.

### Steps to reproduce the problem.

1. Go to Civit Ai tab
2. Press Update models tab
3. click on LoCon radio button
4. click on scan for available updates
5. Error message produced.

### Expected behavior

Should scan the LyCORIS directory and find any outdated files

### System info

* Extension version: ab7856c2
* OS: Windows 11 (up to date)
* SD-WebUI version: Automatic111 (1.6.0)
* Python: 3.10.11
* torch: 2.0.1+cu118
* xformers: 0.0.20
* gradio: 3.41.2

### Console logs

```Shell
in image above.
```

### Additional information

everything else works correctly apart from LyCORIS scanning for updates and for fetching from latest releases on Civit AI

**Comment by ManOrMonster** [comment] 2023-10-23 14:50
Same issue here when trying to search today.

**Comment by zBrendon** [comment] 2023-10-23 16:19
Same. Was working yesterday, but not today. I think there may have been an update that broke it....

**Comment by BlafKing** [comment] 2023-10-23 16:29
My bad all, this was indeed caused by the latest patch since I thought `lyco_dir` was a valid command flag, I've published another hot fix which fixes this issue.
Thanks for reporting!

I'll close this thread since the issue is solved.

**Closed by BlafKing** 2023-10-23 16:29 UTC
Labels: bug

**Comment by AbsolomTDaak** [comment] 2023-10-23 16:43
Thank you, works perfectly again.
