### ISSUE TITLE
[Bug]: Results not working as it should

### ISSUE THREAD

**Issue by NuriDerBurrito** [BlafKing/sd-civitai-browser-plus#122] opened 2023-12-04 11:18 UTC
### Describe the bug.

its been a week i think but for some reason when i use a link or the model name, sometimes it doesnt show the model , sometimes it shows but the image isnt loaded , sometimes its a completely different image , for reference im using sagemaker and didnt have that issue before , example :
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/131478848/465ab030-6280-4de2-86af-4afdf9b62573)
i dont think i did anything since i just also reinstalled sd , so im not sure whats causing it

### Steps to reproduce the problem.

1. Go to extension
2. search a model (example used was"ndgd")
3. bug found

### Expected behavior

should work as expected showing the model and the first image in the preview

### System info

* Extension version: latest
version: [v1.6.1-1-ge1349085](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/e1349085fa689b3e9af836e4416053de9958e4f1)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

### Console logs

```Shell
doesnt show any when searching
```

**Comment by BlafKing** [comment] 2023-12-05 18:41
Thanks for writing in!

There's unfortunately not much I can do here, it looks like this issue isn't caused by the extension itself, since it the model display/image display is simply the result of the return of the API, all this extension does is the display the results it receives.

So if an image or model doesn't show up, then it's likely caused by something outside of this extension :/
Especially since no errors show up in the logs.

I'll close this bug report, since there I can unfortunately not fix this issue.

**Closed by BlafKing** 2023-12-05 18:41 UTC
Labels: bug
