### ISSUE TITLE
[Bug]: This specific LORA gives an error when clicking on it

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#63] opened 2023-10-08 03:53 UTC
### Describe the bug.

https://civitai.com/models/28182/concept-loongchina-dragoneastern-dragon

When clicking on this LORA all the fields say error.

### Steps to reproduce the problem.

1. Choose LORA and type in concept loong
2. Click the LORA
3. Error

### Expected behavior

Not error

### System info

* Extension version: https://github.com/BlafKing/sd-civitai-browser-plus/commit/be5b0f372d0c12a66377d669ee4761d0052368d7
* OS: Windows 10
* SD-WebUI version: 1.5.2
* Python: 3.10.6

### Console logs

```Shell
Model name not found in json_data. (update_model_versions)
Traceback (most recent call last):
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "K:\Stable Diffusion A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "K:\Stable Diffusion A1111\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 733, in update_models_dropdown
    (ret_versions, back_to_top) = _api.update_model_versions(model_name)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by BlafKing** [comment] 2023-10-08 04:45
Thanks for the report!
The error ended up being caused by the usage of `\` in the model name.
Latest hotfix should now properly handle it 👍🏻 

I'll close this thread since the bug should be fixed :)

**Closed by BlafKing** 2023-10-08 04:45 UTC
Labels: bug
