### ISSUE TITLE
[Bug]: LyCORIS folder is back

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#59] opened 2023-10-06 18:24 UTC
### Describe the bug.

I have this option selected:

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/fc94389d-5f4f-4f16-b7c6-6529b16b7487)

But this appears when clicking on a LyCORIS card:

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/d4acb0b4-1f3d-4510-984e-09aed436cf2c)

### Steps to reproduce the problem.

1. Click LyCORIS model card.
2. Be haunted by the reappearance of LyCORIS in your path.

### Expected behavior

Should point to LORA folder when that option is selected.

### System info

* Extension version: 60e11cb
* OS: Windows 11
* SD-WebUI version: 1.6.0
* Python: 3.10.11
* Browser: Brave (private mode)

### Console logs

```Shell
None
```

### Additional information

I was able to work around it by unchecking that option, Apply Settings, Reload UI, check it again, Apply Settings, Reload UI.

But it reverted to the same behavior after closing and restarting auto1111. And trying that now does not fix it.

**Comment by BlafKing** [comment] 2023-10-06 18:29
Probably an oversight caused by the latest patch, thanks for bringing it to my attention!
Should be an easy fix, I'll publish a hotfix for it shortly :)


> Be haunted by the reappearance of LyCORIS in your path.

(Also great description 😂 )

**Comment by BlafKing** [comment] 2023-10-06 18:58
This is now fixed in the latest hotfix, no more LoCon folder :)

Thanks again for notifying me about it!
I'll close this thread now 👍🏻

**Closed by BlafKing** 2023-10-06 18:58 UTC
Labels: bug
