### ISSUE TITLE
[Bug]: The extension cannot be installed on SD.Next

### ISSUE THREAD

**Issue by D0n-A** [BlafKing/sd-civitai-browser-plus#87] opened 2023-10-29 21:06 UTC
### Describe the bug.

Hello. The extension cannot be installed on SD.Next - an alternative to regular Stable Diffusion AUTOMATIC1111. First let you know about it. I am attaching the log.

### Steps to reproduce the problem.

1. Install a clean repository SD.Next on Windows;
2. Find this extension through the extensions menu and install it as usual;
3. Close the command line and restart the interface;
4. Error in console;
5. The extension, unfortunately, does not work.

### Expected behavior
Of course, official compatibility between the extension and the repository is not indicated, plus some functions are present in the repository itself, but I would like to be able to install and fully use the extension. Thank you in advance.

### System info
* Extension version: 1.14.6
* OS: Windows 11
* SD-WebUI version: app=sd.next updated=2023-10-28 hash=e7501126 url=https://github.com/vladmandic/automatic/tree/master
* Python: 3.11.6

### Console logs

```Shell
23:34:55-850186 ERROR    Module load: extensions\sd-civitai-browser-plus\scripts\civitai_api.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ D:\AI\NS02\modules\script_loading.py:21 in load_module                                                              │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:940                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_api.py:14 in <module>                                 │
│                                                                                                                     │
│    13 import scripts.civitai_global as gl                                                                           │
│ ❱  14 import scripts.civitai_download as _download                                                                  │
│    15                                                                                                               │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_download.py:18 in <module>                            │
│                                                                                                                     │
│    17 import scripts.civitai_api as _api                                                                            │
│ ❱  18 import scripts.civitai_file_manage as _file                                                                   │
│    19 try:                                                                                                          │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py:29 in <module>                         │
│                                                                                                                     │
│    28 from_installed = False                                                                                        │
│ ❱  29 queue = not cmd_opts.no_gradio_queue                                                                          │
│    30                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'no_gradio_queue'
23:34:55-903146 ERROR    Module load: extensions\sd-civitai-browser-plus\scripts\civitai_download.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ D:\AI\NS02\modules\script_loading.py:21 in load_module                                                              │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:940                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_download.py:18 in <module>                            │
│                                                                                                                     │
│    17 import scripts.civitai_api as _api                                                                            │
│ ❱  18 import scripts.civitai_file_manage as _file                                                                   │
│    19 try:                                                                                                          │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py:17 in <module>                         │
│                                                                                                                     │
│    16 import scripts.civitai_file_manage as _file                                                                   │
│ ❱  17 import scripts.civitai_download as _download                                                                  │
│    18 try:                                                                                                          │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_download.py:35 in <module>                            │
│                                                                                                                     │
│    34 rpc_secret = "R7T5P2Q9K6"                                                                                     │
│ ❱  35 queue = not cmd_opts.no_gradio_queue                                                                          │
│    36                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'no_gradio_queue'
23:34:55-916876 ERROR    Module load: extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ D:\AI\NS02\modules\script_loading.py:21 in load_module                                                              │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:940                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py:16 in <module>                         │
│                                                                                                                     │
│    15 import scripts.civitai_api as _api                                                                            │
│ ❱  16 import scripts.civitai_file_manage as _file                                                                   │
│    17 import scripts.civitai_download as _download                                                                  │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py:17 in <module>                         │
│                                                                                                                     │
│    16 import scripts.civitai_file_manage as _file                                                                   │
│ ❱  17 import scripts.civitai_download as _download                                                                  │
│    18 try:                                                                                                          │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_download.py:35 in <module>                            │
│                                                                                                                     │
│    34 rpc_secret = "R7T5P2Q9K6"                                                                                     │
│ ❱  35 queue = not cmd_opts.no_gradio_queue                                                                          │
│    36                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'no_gradio_queue'
23:34:55-934052 ERROR    Module load: extensions\sd-civitai-browser-plus\scripts\civitai_gui.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ D:\AI\NS02\modules\script_loading.py:21 in load_module                                                              │
│                                                                                                                     │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                          │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                         │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                          │
│ in exec_module:940                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py:10 in <module>                                 │
│                                                                                                                     │
│     9 import scripts.civitai_global as gl                                                                           │
│ ❱  10 import scripts.civitai_download as _download                                                                  │
│    11 import scripts.civitai_file_manage as _file                                                                   │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_download.py:18 in <module>                            │
│                                                                                                                     │
│    17 import scripts.civitai_api as _api                                                                            │
│ ❱  18 import scripts.civitai_file_manage as _file                                                                   │
│    19 try:                                                                                                          │
│                                                                                                                     │
│ D:\AI\NS02\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py:29 in <module>                         │
│                                                                                                                     │
│    28 from_installed = False                                                                                        │
│ ❱  29 queue = not cmd_opts.no_gradio_queue                                                                          │
│    30                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'no_gradio_queue'
```

**Comment by BlafKing** [comment] 2023-10-30 10:25
Thx for the report! This is caused by a flag that I presume SD Next does not use, I'll add a try except block around it so that it defaults to True if the flag isn't found 👍🏻

**Comment by James-Willer** [comment] 2023-10-30 13:52
SD Next has the flag, but its named disable_queue

**Comment by BlafKing** [comment] 2023-10-30 13:54
> SD Next has the flag, but its named disable_queue

Good to know, thx! I'll make sure to use that instead when `no_gradio_queue` fails :)

**Comment by BlafKing** [comment] 2023-10-30 14:07
Issue is now fixed in the latest commit! 👍🏻

**Closed by BlafKing** 2023-10-30 14:07 UTC
Labels: bug, WIP
