### ISSUE TITLE
[Bug]: Tile Count not working

### ISSUE THREAD

**Issue by bankenichi** [BlafKing/sd-civitai-browser-plus#141] opened 2023-12-19 04:58 UTC
### Describe the bug.

Looks like tile count isnt working, it will only show 15 tiles per page no matter what it is actually set to.

### Steps to reproduce the problem.

1. Go to Browser
2. Set tile count to 100 
3. Run any search with 16+ results
4. Returns 15 tiles on page 1
5. Set tile count to 10
6. 3. Run any search with 11+ results
7. Still returns 15 tiles on page 1

### Expected behavior

Each page should show tiles equal to tile count

### System info

* Extension version:3.1.1
* OS:Win10
* SD-WebUI version:v1.7.0
* Python:3.10.6

### Console logs

```Shell


Already up to date.
venv "E:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132
Installing Miaoshou assistant requirement: gradio_client==0.5.0
Installing Miaoshou assistant requirement: requests==2.31.0
Installing Miaoshou assistant requirement: urllib3==2.0.6
Installing Miaoshou assistant requirement: tqdm==4.64.0
ReActor preheating... Device: CUDA
#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 136983e89859fd0477b4a437ed333142a6aa29a4
SD-WebUI revision: cf2772fab0af5573da775e7437e6acdca424f26e

Checking Civitai Link requirements...

#######################################################################################################
Launching Web UI with arguments: --opt-sdp-attention --no-half-vae --theme dark --autolaunch
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.11.1, num models: 27
logs_location: E:\Stable Diffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\logs
CivitAI Browser+: Aria2 RPC started
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 330.60it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 500.51it/s]
ControlNet preprocessor location: E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-18 22:53:27,656 - ControlNet - INFO - ControlNet v1.1.423
2023-12-18 22:53:27,934 - ControlNet - INFO - ControlNet v1.1.423
[sd-webui-freeu] Controlnet support: *enabled*
22:53:29 - ReActor - STATUS - Running v0.6.0-a2
Civitai: API loaded
Loading weights [cccb73cda9] from E:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\sexyToon3D_v10.safetensors
2023-12-18 22:53:30,389 - AnimateDiff - INFO - Injecting LCM to UI.
Creating model from config: E:\Stable Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
2023-12-18 22:53:33,442 - AnimateDiff - INFO - Hacking i2i-batch.
Civitai Helper: Set Proxy:
add tab
[([button, button, button, button, button], button, gallery), ([button, button, button, button, button], button, gallery)]
Loading VAE weights specified in settings: E:\Stable Diffusion\stable-diffusion-webui\models\VAE\anythingKlF8Anime2VaeFtMse840000_anything.safetensors
Applying attention optimization: sdp... done.
2023-12-18 22:54:03,177 - AnimateDiff - INFO - Hacking i2i-batch is already done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing info files
Civitai Link: Connecting to Civitai Link Server
Model loaded in 40.0s (load weights from disk: 2.1s, create model: 0.6s, apply weights to model: 25.2s, load VAE: 1.7s, move model to device: 1.9s, load textual inversion embeddings: 5.3s, calculate empty prompt: 3.2s).
Civitai Link: Connected to Civitai Link Server
Civitai: Check resources for missing preview images
Startup time: 131.9s (initial startup: 0.1s, prepare environment: 54.2s, import torch: 11.1s, import gradio: 2.8s, setup paths: 1.6s, initialize shared: 1.2s, other imports: 1.5s, setup codeformer: 0.3s, list SD models: 1.3s, load scripts: 17.4s, create ui: 34.0s, gradio launch: 2.9s, app_started_callback: 3.2s).
Civitai Link: Joined room 
Civitai Link: Presence update: SD: 1, Clients: 1
Civitai Link: Connected to Civitai Instance
Civitai Link: Incoming Command: activities:list
Civitai Link: Incoming Command: resources:list
Civitai: Found 0 resources missing info files
Civitai: No info found on Civitai
Civitai: Found 57 resources missing preview images
Civitai: No preview images found on Civitai
CivitAI Browser+: Cannot save settings, failed to open "<_io.TextIOWrapper name='E:\\Stable Diffusion\\stable-diffusion-webui\\ui-config.json' mode='r' encoding='cp1252'>"
Please try to manually repair the file or remove it to reset settings.


### Additional information

Kept trying an eventually got that last message on the log,

**Comment by BlafKing** [comment] 2023-12-19 11:09
Thanks for reporting.

I can't seem to re-create the issue you described:

https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/e0e00696-6748-4682-8a35-1d8e6dbd3a43

Just to verify, did you try to load the pages in the same way that I did in the preview above?

I can't really think of anything that could cause this issue, since no one else has reported this before, and the code for page count insertion has remained the same for a long time.
There's unfortunately not much I can do without more info/error logs :/

(The issue where it was unable to save the settings also shouldn't be able to affect this)

**Comment by BlafKing** [comment] 2023-12-19 15:41
Thanks for chipping in! @AbsolomTDaak 

I'll look into the issue a bit further, I myself don't experience any issues with 1.7.0, but upon inspection I see that some issues could maybe arise from the way that I currently implement fetching and setting the tile_count.

It's pretty bodgie, I currently set it as a global variable, instead of fetching the value when it should be used, which should be a better and more robust approach, so I'll go and implement that to see if it helps fix the issue! :)

**Comment by bankenichi** [comment] 2023-12-19 17:06
I went and manually edited ui-config.json and set the tile count to 15, that seems to have gotten it unstuck, but it will still return the same error message if I try to save a different tile count as default from the webui.

Thanks for all your hard work.

**Comment by bankenichi** [comment] 2023-12-19 21:21
> Thanks for reporting.
> 
> I can't seem to re-create the issue you described:
> 
>  Preview_tile.mp4 
> Just to verify, did you try to load the pages in the same way that I did in the preview above?
> 
> I can't really think of anything that could cause this issue, since no one else has reported this before, and the code for page count insertion has remained the same for a long time. There's unfortunately not much I can do without more info/error logs :/
> 
> (The issue where it was unable to save the settings also shouldn't be able to affect this)

I did follow those steps exactly the first time I noticed.

It seems that my defaults were set to 15 at some point and the extension wasn't able to update it from webui. I actually went and set it to 100 in the ui-config and closed and reopned a1111, it didn't work. I went back and set it to 15 and it started working, so when I change it in webui it will work for that session.

It will still not save the defaults tho.

**Comment by BlafKing** [comment] 2023-12-21 21:44
The latest version ([v3.2.0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/d21758863a0605f5139b1f5f49af0a4e00880b02)) should now hopefully fix the issues mentioned in this thread!

It looks like the error with saving the filter settings was caused by an incorrect encoding, so I've forced it to be "utf8", which should be what the ui-config.json is encoded in.

The tile count being incorrect should also hopefully be fixed now, since I've used a better method of providing the actual tile count to the API request!

Please let me know if you're still experiencing any issues! :)

**Comment by BlafKing** [comment] 2023-12-28 00:41
Since there have been no updates in a while I will close this bug report.
Please feel free to send another message here if the issue still exists! :)

**Closed by BlafKing** 2023-12-28 00:41 UTC
Labels: bug, WIP
