### ISSUE TITLE
[Bug]: Getting "UnboundLocalError: local variable 'api_response' referenced before assignment" Error

### ISSUE THREAD

**Issue by lundejd** [BlafKing/sd-civitai-browser-plus#60] opened 2023-10-06 18:33 UTC
### Describe the bug.

When trying to update Loras or TextualInversions I can load installed models to the browser but when I click on Scan for Available Updates an error shows up on the console:

File "/home/ubuntu/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 574, in file_scan
    updated_models, outdated_models = version_match(file_paths, api_response)
UnboundLocalError: local variable 'api_response' referenced before assignment

### Steps to reproduce the problem.

1. Go to Civit AI tab 
2. Click "Update Models"
3. Select Lora
4. Click "load installed models to browser"
5. Click "Scan for Available Updates"
6. shows "error" in red inside an oval

### Expected behavior

Should show me the Loras that are outdated like it does for checkpoints (which does work)

### System info

OS: Ubuntu
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.10  •  torch: 2.0.1+cu118  •  xformers: 0.0.17  •  gradio: 3.41.2  •  checkpoint: [76be5be1b2](https://google.com/search?q=76be5be1b2a317e38dbe80a9b33d6a35db5a27883ba0569e7a1624281f2a6c95)

Extension version: [60e11cba](https://github.com/BlafKing/sd-civitai-browser-plus/commit/60e11cbaf9e19405b4e3c8ed5c62c107d9394602)

### Console logs

```Shell
File "/home/ubuntu/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 574, in file_scan
    updated_models, outdated_models = version_match(file_paths, api_response)
UnboundLocalError: local variable 'api_response' referenced before assignment
```

### Additional information

I do have Loras and Textual inversions that do not exist on Civitai

**Comment by BlafKing** [comment] 2023-10-06 20:55
Thanks for reporting the issue!

Just to make sure, are these all the errors that occur?
I'm wondering since the error: `UnboundLocalError: local variable 'api_response' referenced before assignment`
Only occurs if something before it has gone wrong causing the api_response data to not exist.

The only other case in which this can happen (as far as I can tell) is if you have pressed the `Load all installed models` followed by pressing the `Scan for available updates` button, without first pressing `Load installed models to browser`

This can also happen if you attempt to use both the `Scan for available updates` at the same time as
`Load all installed models`, which isn't possible since they both use the same function.

Please let me know if your error was caused by something else, I'll also make sure to disable the other buttons whilst the other functions are running to avoid this error.

**Comment by lundejd** [comment] 2023-10-06 21:18
You are right, there is more to the error (below). Also, I found if I kill the process and reload stable-diffusion I can run one of the selections and process it, but if I go back and try another it gives the error again. This is why I could do checkpoints but nothing else. This time I did loras but couldn’t do anything else.

Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 574, in file_scan
    updated_models, outdated_models = version_match(file_paths, api_response)
UnboundLocalError: local variable 'api_response' referenced before assignment





From: Tom ***@***.***>
Date: Friday, October 6, 2023 at 3:55 PM
To: BlafKing/sd-civitai-browser-plus ***@***.***>
Cc: John Lundell ***@***.***>, Author ***@***.***>
Subject: Re: [BlafKing/sd-civitai-browser-plus] [Bug]: Getting "UnboundLocalError: local variable 'api_response' referenced before assignment" Error (Issue #60)

Thanks for reporting the issue!

Just to make sure, are these all the errors that occur?
I'm wondering since the error: UnboundLocalError: local variable 'api_response' referenced before assignment
Only occurs if something before it has gone wrong causing the api_response data to not exist.

The only other case in which this can happen (as far as I can tell) is if you have pressed the Load all installed models followed by pressing the Scan for available updates button, without first pressing Load installed models to browser

This can also happen if you attempt to use both the Scan for available updates at the same time as
Load all installed models, which isn't possible since they both use the same function.

Please let me know if your error was caused by something else, I'll also make sure to disable the other buttons whilst the other functions are running to avoid this error.

**Comment by BlafKing** [comment] 2023-10-06 21:24
Good to know! I'll publish an update now which will hopefully fix your issue.
Please let me know if the latest commit fixes it :)

**Comment by lundejd** [comment] 2023-10-06 21:33
That did it! Thanks!

This is perhaps the best plugin I’ve installed since ControlNet and Adetailer.  My server is remote so downloading isn’t easy as I have to remote in, now I can just do it from my browser. Thanks!

From: Tom ***@***.***>
Date: Friday, October 6, 2023 at 4:24 PM
To: BlafKing/sd-civitai-browser-plus ***@***.***>
Cc: John Lundell ***@***.***>, Author ***@***.***>
Subject: Re: [BlafKing/sd-civitai-browser-plus] [Bug]: Getting "UnboundLocalError: local variable 'api_response' referenced before assignment" Error (Issue #60)

Good to know! I'll publish an update now which will hopefully fix your issue.
Please let me know if the latest commit fixes it :)

**Comment by BlafKing** [comment] 2023-10-06 21:41
Awesome, glad to hear that worked! 😄 

I'll close this thread now since the error is resolved 👍🏻

**Closed by BlafKing** 2023-10-06 21:41 UTC
Labels: bug
