### ISSUE TITLE
[Bug]: .MissingSchema: Invalid URL 'None'

### ISSUE THREAD

**Issue by peppignoo** [BlafKing/sd-civitai-browser-plus#159] opened 2024-01-07 13:37 UTC
### Describe the bug.

The models installed on automatic 1111 are not loaded generating an error in the console

### Steps to reproduce the problem.

1. Go to CivitAI Browser+ tab. .... 
2. Go to Update models
3. Press ALL 
4. Press load all installed models

### Expected behavior

Templates installed on automatic 1111 are recognized by the extension

### System info

* Extension version:[15b2f66e]
* OS: Windows 11
* SD-WebUI version: automatic 1111 [v1.7.0]
* Python: 3.10.6

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd.webui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 826, in file_scan
    response = requests.get(api_url, timeout=(10,30))
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\sd.webui\webui\venv\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

**Comment by BlafKing** [comment] 2024-01-07 14:23
Thanks for reporting!

I'm unsure what could cause this error, since I'm unable to re-create the error myself.
I've just published a hotfix that prints more info which will hopefully let me identify the issue, if you could retry and post the logs after updating to the latest version that would be helpful!

**Comment by peppignoo** [comment] 2024-01-07 16:25
Thanks for the reply, I updated the extension as you told me now this appears in the console:
CivitAI Browser+: ERROR: api_url is None
model IDs: []
model chunks: []
URL index: {}
CivitAI Browser+: An error occured, could not retrieve the API URL: None
Traceback (most recent call last):
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd.webui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 1001, in load_to_browser
    model_list_return = _api.update_model_list(from_installed=True, tile_count=tile_count)
  File "C:\sd.webui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 536, in update_model_list
    gr.Dropdown.update(choices=[v for k, v in model_dict.items()], value="", interactive=True), # Model List
UnboundLocalError: local variable 'model_dict' referenced before assignment

**Comment by peppignoo** [comment] 2024-01-07 16:30
This message appears in the GUI: The Civit-API has timed out, please try again.
The servers might be too busy or the selected model could not be found

**Comment by BlafKing** [comment] 2024-01-09 01:38
Well, turns out I made a really silly mistake where the checkbox for generating a hash for a model is inverted.

The issue was most likely caused by the fact that your models were not downloaded with this extension, it's required to generate a hash and retrieve a model ID for each model for it to be searchable with the CivitAI API.
Generating a hash is a one time process as described in the UI, so the first run will take much longer than the second time :) (dependant on how many models you have)

The latest update should fix your issue as long as you have the `One-Time Hash Generation for externally downloaded models.` option turned on!

**Comment by peppignoo** [comment] 2024-01-11 16:01
Thanks, everything works perfectly

**Comment by BlafKing** [comment] 2024-01-11 16:30
Perfect!
I'll go ahead and close this bug report since it's resolved :)

**Closed by BlafKing** 2024-01-11 16:30 UTC
Labels: bug, WIP
