### ISSUE TITLE
[Bug]: Failed to start download: 'result' - with Aria2

### ISSUE THREAD

**Issue by gurukast** [BlafKing/sd-civitai-browser-plus#79] opened 2023-10-21 10:27 UTC
### Describe the bug.

Does not download, and generates that in console 
Failed to start download: 'result'
Error occured during download of "M:\AI\A160\stable-diffusion-webui\models\Lora\SDXL\ling1.safetensors".

Was working fine before, so not sure what happened.
tried enabling Show Aria2 logs in CMD , but didnt give any more details when an error occurs.

### Steps to reproduce the problem.

Attempt to download anything

### Expected behavior

A successful download

### System info

* Extension version:
Windows 10
 version: [v1.6.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

### Console logs

```Shell
Failed to start download: 'result'
Error occured during download of "M:\AI\A160\stable-diffusion-webui\models\Lora\SDXL\ling1.safetensors".
```

### Additional information

Works if Aria2 is disabled

**Comment by BlafKing** [comment] 2023-10-21 23:08
Sorry to hear you're experiencing issues.
Just to make sure, did you fully restart SD-WebUI after enabling `Show Aria2 logs in CMD`?

You need to fully restart the full program, not just reloading the UI.

**Comment by BlafKing** [comment] 2023-10-21 23:45
Looks like I've successfully recreated the error, I think it's associated with the RPC Secret being incorrect.
I'll try to fix this by making the RPC Secret static, hopefully this will solve your issue.

I'll also make the error more descriptive, so that it will give me more information if this hasn't fixed the issue.
Please let me know if you're still experiencing the issue on the latest hotfix! :)

**Comment by callit** [comment] 2023-10-22 04:26
Wow, I literally just started having this same problem.  I had installed some other extensions so I was thinking there might be a conflict, but this is good to know.  I'll keep an eye out for the patch!

**Comment by callit** [comment] 2023-10-22 04:42
Still failing for me.  This is the error I receive: 

`Failed to start download: Failed to start download: {'id': '1', 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'Unauthorized'}}`

When I enable logging I get this:

```
An error occurred: list index out of range
An error occurred: list index out of range
An error occurred: list index out of range
An error occurred: list index out of range
An error occurred: list index out of range
Exception in thread Thread-33 (download_file):
Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 232, in download_file
    if progress:
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 505, in __len__
    return self.iterables[-1].length
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\sd\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 256, in download_file
    if progress:
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 505, in __len__
    return self.iterables[-1].length
IndexError: list index out of range
```

**Comment by gurukast** [comment] 2023-10-22 06:01
Using v1.14.6 (Hotfix), same error as above

`Failed to start download: Failed to start download: {'id': '1', 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'Unauthorized'}}`

**Comment by BlafKing** [comment] 2023-10-22 15:58
Really odd, this error still indicates that the RPC Secret is incorrect, which shouldn't be possible since the string is static and does not change.

The only other thing I can think of is that another program is also using Aria2 on the same port, I've changed the port that Aria2 runs on in the latest hotfix, please let me know if that has resolved the issue, if not, I will resort back to not using an RPC Secret at all.

**Comment by gurukast** [comment] 2023-10-22 18:06
> Really odd, this error still indicates that the RPC Secret is incorrect, which shouldn't be possible since the string is static and does not change.
> 
> The only other thing I can think of is that another program is also using Aria2 on the same port, I've changed the port that Aria2 runs on in this extension in the latest hotfix, please let me know if that has resolved the issue, if not, I will resort back to not using an RPC Secret at all.

It works now!

**Comment by BlafKing** [comment] 2023-10-22 18:34
Awesome, glad to hear :)

I'll close this thread since the issue is resolved!

**Closed by BlafKing** 2023-10-22 18:34 UTC
Labels: bug, WIP
