### ISSUE TITLE
[BUG] Unable to finish scan for updates for large model sets

### ISSUE THREAD

**Issue by mosherc** [BlafKing/sd-civitai-browser-plus#55] opened 2023-10-05 01:56 UTC
**Describe the bug**
Unable to finish scan for updates for large model sets. Works fine for smaller sets, like my checkpoints, textualinversions, etc.

**To Reproduce**
1. Have a lot of LORAs
2. Click on "Update Models"
3. Select "LORA"
4. Click "Scan"
5. Wait for loading bar
6. See error pill and below error in console:
```
Error: Received status code 400
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 527, in file_scan
    api_response['items'] = all_items
UnboundLocalError: local variable 'api_response' referenced before assignment
```

**Expected behavior**
Scan should complete, and I should be able to load the updated models into the browser.

**Screenshots**

**Additional context**
* Extension version: [73f84dda](https://github.com/BlafKing/sd-civitai-browser-plus/commit/73f84ddab081347e23161737a92dbe7d8b418db0)
* OS: Windows 11
* SD version: 1.6.0
* Python: 3.10.8
* Any Additional info

**Comment by BlafKing** [comment] 2023-10-05 10:46
Thanks for letting me know! 
This is probably caused by providing too many ID's in a single request to the CivitAI API, I'll try to debug and experiment with splitting the API request in to multiple request if there are too many ID's provided! :)

**Comment by BlafKing** [comment] 2023-10-05 17:20
Update v1.14.1 now includes the URL that it attempted to use for the API request.
Could you retry and provide the URL that gets printed when the error occurs?
It would also be helpful if you could tell me how many LORA's you tried to use and which scanning option you used.
(Assigned tags, Available updates, All installed)

This would help me to bug test the issue!

**Comment by mosherc** [comment] 2023-10-05 18:17
> Update v1.14.1 now includes the URL that it attempted to use for the API request. Could you retry and provide the URL that gets printed when the error occurs? It would also be helpful if you could tell me how many LORA's you tried to use and which scanning option you used. (Assigned tags, Available updates, All installed)
> 
> This would help me to bug test the issue!

Sure, I neglected to use exact wording, this is "Scan for available updates". I have 1327 safetensor files in my lora folder, ~103GB. Just to debug a bit, I cut and paste individual LORA subdirectories into the LORA directory so it would just scan one at a time (ex. characters only), and it worked fine. I have 8 subdirectories, so seems like the breaking point is somewhere around 200 or more LORAs possibly.

```
Error: Received status code 400 with URL:
https://civitai.com/api/v1/models?limit=100&ids=98652&ids=138279&ids=141311&ids=46303&ids=151012&ids=129128&ids=17223&ids=87363&ids=128447&ids=128952&ids=121668&ids=9432&ids=70849&ids=42214&ids=8723&ids=115720&ids=54723&ids=55000&ids=12657&ids=28559&ids=4959&ids=21059&ids=57006&ids=129056&ids=60090&ids=6693&ids=81268&ids=95840&ids=37006&ids=23594&ids=147300&ids=57015&ids=100939&ids=20682&ids=88234&ids=120645&ids=39068&ids=21317&ids=127942&ids=120823&ids=129588&ids=132465&ids=138290&ids=25485&ids=142643&ids=82811&ids=153974&ids=56920&ids=73690&ids=43084&ids=8399&ids=64628&ids=111841&ids=111590&ids=63722&ids=27569&ids=7701&ids=111955&ids=128879&ids=15599&ids=146626&ids=51864&ids=13502&ids=143206&ids=17372&ids=8243&ids=147750&ids=18413&ids=59257&ids=143822&ids=9100&ids=112351&ids=88479&ids=129628&ids=38153&ids=110488&ids=94912&ids=127533&ids=60621&ids=150444&ids=112135&ids=18649&ids=93878&ids=127081&ids=147295&ids=58686&ids=65283&ids=128860&ids=83626&ids=13048&ids=88398&ids=30234&ids=73754&ids=26478&ids=92706&ids=116855&ids=103011&ids=129042&ids=50030&ids=84740&ids=39257&ids=17875&ids=113847&ids=8877&ids=24311&ids=8349&ids=17302&ids=132751&ids=108641&ids=63013&ids=52023&ids=144404&ids=116407&ids=74593&ids=131339&ids=128718&ids=20432&ids=44587&ids=122183&ids=45566&ids=19350&ids=61209&ids=8398&ids=117977&ids=15038&ids=146603&ids=53271&ids=126529&ids=147296&ids=19620&ids=16316&ids=137173&ids=22956&ids=48875&ids=43199&ids=96649&ids=47966&ids=132533&ids=52577&ids=15630&ids=69357&ids=114794&ids=128972&ids=88411&ids=60036&ids=72282&ids=16817&ids=46153&ids=69431&ids=116919&ids=105433&ids=23879&ids=129741&ids=88830&ids=61418&ids=131407&ids=127884&ids=102582&ids=134694&ids=127158&ids=114339&ids=7958&ids=10019&ids=71084&ids=48363&ids=135921&ids=111851&ids=22732&ids=84627&ids=9155&ids=115689&ids=124214&ids=120975&ids=104255&ids=112465&ids=36615&ids=15112&ids=80905&ids=135868&ids=77310&ids=101999&ids=42906&ids=112594&ids=87584&ids=56486&ids=118156&ids=104271&ids=102982&ids=151509&ids=55879&ids=112001&ids=87587&ids=147485&ids=156270&ids=114580&ids=60724&ids=93626&ids=89941&ids=72840&ids=61675&ids=10554&ids=146517&ids=131864&ids=46199&ids=129159&ids=60423&ids=11744&ids=130269&ids=9067&ids=131294&ids=145948&ids=124355&ids=58012&ids=153301&ids=49044&ids=10402&ids=12823&ids=134187&ids=17883&ids=13753&ids=143643&ids=135706&ids=46315&ids=133292&ids=113321&ids=130089&ids=8179&ids=44524&ids=117171&ids=123830&ids=30675&ids=47077&ids=60624&ids=10032&ids=22551&ids=23320&ids=71626&ids=115023&ids=14224&ids=72571&ids=16346&ids=39104&ids=154333&ids=59233&ids=127915&ids=135294&ids=60046&ids=17425&ids=115062&ids=80023&ids=97042&ids=71728&ids=132937&ids=83816&ids=140589&ids=127903&ids=130223&ids=123226&ids=84028&ids=28309&ids=24530&ids=116310&ids=126763&ids=83150&ids=154325&ids=100811&ids=73756&ids=94182&ids=92026&ids=122423&ids=117027&ids=90888&ids=57737&ids=115078&ids=68097&ids=17712&ids=10424&ids=30403&ids=48192&ids=95579&ids=126293&ids=59773&ids=77571&ids=49841&ids=119194&ids=54258&ids=153261&ids=14287&ids=65090&ids=149369&ids=9014&ids=82128&ids=20975&ids=102579&ids=85412&ids=45289&ids=71445&ids=80836&ids=55047&ids=106762&ids=105976&ids=117520&ids=91277&ids=11569&ids=146836&ids=24891&ids=95236&ids=143478&ids=111038&ids=118867&ids=99145&ids=98531&ids=24960&ids=14673&ids=151530&ids=42642&ids=80756&ids=21848&ids=134153&ids=46252&ids=59245&ids=89125&ids=118896&ids=81262&ids=118633&ids=17455&ids=15111&ids=147671&ids=112806&ids=113697&ids=84349&ids=153562&ids=115694&ids=59404&ids=128483&ids=97778&ids=54036&ids=128836&ids=93201&ids=119077&ids=85366&ids=55613&ids=112238&ids=115054&ids=19403&ids=118842&ids=112242&ids=46423&ids=140302&ids=12195&ids=154195&ids=19719&ids=63307&ids=34862&ids=75122&ids=30658&ids=18751&ids=114479&ids=121303&ids=87622&ids=130268&ids=95906&ids=32589&ids=129576&ids=46189&ids=115838&ids=27000&ids=87590&ids=57214&ids=15815&ids=53870&ids=18386&ids=25282&ids=70192&ids=12852&ids=127819&ids=137062&ids=23984&ids=154356&ids=109119&ids=129585&ids=55730&ids=124692&ids=11088&ids=42903&ids=21905&ids=94231&ids=130962&ids=113051&ids=112658&ids=37269&ids=111059&ids=142887&ids=9221&ids=129801&ids=126564&ids=56586&ids=58390&ids=105329&ids=129549&ids=18299&ids=25869&ids=15074&ids=17661&ids=140714&ids=72077&ids=129406&ids=134097&ids=56576&ids=13308&ids=13127&ids=71813&ids=70619&ids=93489&ids=18051&ids=36945&ids=58518&ids=155294&ids=135559&ids=18291&ids=35283&ids=17361&ids=24583&ids=80970&ids=111432&ids=98256&ids=131568&ids=131291&ids=74522&ids=24195&ids=48985&ids=59465&ids=31090&ids=89630&ids=150361&ids=13046&ids=53278&ids=134240&ids=56810&ids=154212&ids=24866&ids=99930&ids=96490&ids=23119&ids=101723&ids=115259&ids=21726&ids=66719&ids=131278&ids=25258&ids=22640&ids=46396&ids=23072&ids=78754&ids=146715&ids=16775&ids=26944&ids=67976&ids=103190&ids=81327&ids=20628&ids=85571&ids=104711&ids=155296&ids=125352&ids=129009&ids=114327&ids=137744&ids=38953&ids=154314&ids=113427&ids=16014&ids=27483&ids=89412&ids=117111&ids=108909&ids=115103&ids=37219&ids=62761&ids=134579&ids=6638&ids=130463&ids=129179&ids=11768&ids=84148&ids=82794&ids=93307&ids=16186&ids=21948&ids=81480&ids=67077&ids=153975&ids=15976&ids=7328&ids=141842&ids=155437&ids=21831&ids=44960&ids=15027&ids=11532&ids=102846&ids=100923&ids=145987&ids=36461&ids=92704&ids=33712&ids=22702&ids=104143&ids=86142&ids=38199&ids=83494&ids=62880&ids=10816&ids=92444&ids=144617&ids=51779&ids=22097&ids=55032&ids=103175&ids=6100&ids=132429&ids=58136&ids=134025&ids=88275&ids=74046&ids=154582&ids=148182&ids=115848&ids=116333&ids=90532&ids=135565&ids=42066&ids=20824&ids=127879&ids=84207&ids=64029&ids=52128&ids=117786&ids=42002&ids=98450&ids=25803&ids=155045&ids=48341&ids=108108&ids=128914&ids=17379&ids=83823&ids=20120&ids=44404&ids=70854&ids=84542&ids=23319&ids=76383&ids=130362&ids=57501&ids=98142&ids=119191&ids=139779&ids=51136&ids=52377&ids=117254&ids=155136&ids=149665&ids=147716&ids=32172&ids=75947&ids=87728&ids=46522&ids=124724&ids=91380&ids=124872&ids=154987&ids=77978&ids=9972&ids=43711&ids=35383&ids=83990&ids=86939&ids=20040&ids=41282&ids=86447&ids=37870&ids=90041&ids=97630&ids=136001&ids=152353&ids=90718&ids=82946&ids=58736&ids=111936&ids=109196&ids=99948&ids=29232&ids=114392&ids=115406&ids=62414&ids=101009&ids=114221&ids=110492&ids=78135&ids=95035&ids=94551&ids=146994&ids=106212&ids=78256&ids=81180&ids=129482&ids=34839&ids=149337&ids=118249&ids=64867&ids=124672&ids=121870&ids=6888&ids=57686&ids=18658&ids=48952&ids=13910&ids=80257&ids=116311&ids=155280&ids=8679&ids=101548&ids=12237&ids=53953&ids=100928&ids=123223&ids=122195&ids=18177&ids=55365&ids=8682&ids=16055&ids=110932&ids=123855&ids=104245&ids=30287&ids=53435&ids=115048&ids=147286&ids=130680&ids=20648&ids=92890&ids=80251&ids=111022&ids=130526&ids=20173&ids=18592&ids=152877&ids=74312&ids=102217&ids=30410&ids=130193&ids=18927&ids=130495&ids=126281&ids=42492&ids=149793&ids=67997&ids=128000&ids=21990&ids=7887&ids=79653&ids=7706&ids=95341&ids=107462&ids=78033&ids=140902&ids=128904&ids=32541&ids=114350&ids=85322&ids=18724&ids=136438&ids=14442&ids=44615&ids=26124&ids=21787&ids=94284&ids=154349&ids=131463&ids=156280&ids=79326&ids=105555&ids=115044&ids=111793&ids=81176&ids=17263&ids=19114&ids=129489&ids=27174&ids=27708&ids=128915&ids=128095&ids=17658&ids=139842&ids=91780&ids=106800&ids=90253&ids=121207&ids=146171&ids=39061&ids=60661&ids=134866&ids=94805&ids=106552&ids=17391&ids=34372&ids=20512&ids=14153&ids=20465&ids=39192&ids=17675&ids=146076&ids=18376&ids=20355&ids=115108&ids=147381&ids=110380&ids=47286&ids=128917&ids=54854&ids=94157&ids=95440&ids=142361&ids=131822&ids=137119&ids=98054&ids=68838&ids=131835&ids=120880&ids=136334&ids=27375&ids=19668&ids=59739&ids=78921&ids=17258&ids=8949&ids=42515&ids=66031&ids=117589&ids=14087&ids=114568&ids=61382&ids=136710&ids=72086&ids=120860&ids=140118&ids=119201&ids=92373&ids=81434&ids=126534&ids=89051&ids=126227&ids=103473&ids=44638&ids=114351&ids=27513&ids=60492&ids=114512&ids=127926&ids=142782&ids=27851&ids=75594&ids=24310&ids=12423&ids=131412&ids=24869&ids=72431&ids=21807&ids=12726&ids=74223&ids=44625&ids=73192&ids=113820&ids=132578&ids=137258&ids=51621&ids=49824&ids=114989&ids=153829&ids=145887&ids=114079&ids=141772&ids=129015&ids=92557&ids=154145&ids=153710&ids=39768&ids=129030&ids=16955&ids=114949&ids=49732&ids=117940&ids=32810&ids=88573&ids=129503&ids=22123&ids=120464&ids=19310&ids=87813&ids=129651&ids=26979&ids=33208&ids=155022&ids=16230&ids=155302&ids=26350&ids=137160&ids=8451&ids=32827&ids=73981&ids=14926&ids=89668&ids=140965&ids=19695&ids=28811&ids=60137&ids=7094&ids=31081&ids=69674&ids=88331&ids=114344&ids=154996&ids=130163&ids=130395&ids=140359&ids=7271&ids=60059&ids=97258&ids=20921&ids=13406&ids=64619&ids=57287&ids=100031&ids=45542&ids=114487&ids=87066&ids=67776&ids=130014&ids=72566&ids=114434&ids=152603&ids=111323&ids=33251&ids=95568&ids=129317&ids=55411&ids=94205&ids=94714&ids=135061&ids=128417&ids=18527&ids=15376&ids=94218&ids=47694&ids=129895&ids=59726&ids=19572&ids=88402&ids=115099&ids=103023&ids=83448&ids=109818&ids=47931&ids=140595&ids=10934&ids=22396&ids=106532&ids=71962&ids=75068&ids=88396&ids=32897&ids=47122&ids=88522&ids=114505&ids=95938&ids=7300&ids=113845&ids=128524&ids=108464&ids=101043&ids=57821&ids=12835&ids=146036&ids=80563&ids=85165&ids=115160&ids=43292&ids=88312&ids=28360&ids=113865&ids=21555&ids=103007&ids=64877&ids=82831&ids=9714&ids=28924&ids=100927&ids=25921&ids=49840&ids=129355&ids=13224&ids=114516&ids=89176&ids=92715&ids=140653&ids=23885&ids=6951&ids=92853&ids=40842&ids=24001&ids=24087&ids=127958&ids=115660&ids=147114&ids=19295&ids=12265&ids=124452&ids=55374&ids=106906&ids=53151&ids=99256&ids=10564&ids=117000&ids=62428&ids=51875&ids=23766&ids=142914&ids=122143&ids=54934&ids=113823&ids=111225&ids=90291&ids=7613&ids=23333&ids=119818&ids=139250&ids=82098&ids=89750&ids=87693&ids=100935&ids=20683&ids=84144&ids=116432&ids=8158&ids=16722&ids=74699&ids=130539&ids=26541&ids=16065&ids=52885&ids=34106&ids=141321&ids=81314&ids=107092&ids=100929&ids=87037&ids=39229&ids=45440&ids=110199&ids=60665&ids=86453&ids=29763&ids=57112&ids=8190&ids=142113&ids=111644&ids=9651&ids=27892&ids=18323&ids=49707&ids=80965&ids=129867&ids=156259&ids=40864&ids=114396&ids=137710&ids=130186&ids=136010&ids=87291&ids=134794&ids=57259&ids=25396&ids=85312&ids=139943&ids=51650&ids=118697&ids=106178&ids=152400&ids=10489&ids=124696&ids=61246&ids=10844&ids=155214&ids=110690&ids=84938&ids=141780&ids=5067&ids=94566&ids=64262&ids=143152&ids=44215&ids=117375&ids=60304&ids=26818&ids=122917&ids=130298&ids=113563&ids=26824&ids=6610&ids=57753&ids=85916&ids=126535&ids=77117&ids=9950&ids=145938&ids=156891&ids=27386&ids=117980&ids=26871&ids=28352&ids=119558&ids=93658&ids=26948&ids=114226&ids=138772&ids=7327&ids=48676&ids=37131&ids=8688&ids=36692&ids=41879&ids=156309&ids=5115&ids=146365&ids=37343&ids=141060&ids=21342&ids=42599&ids=48557&ids=63490&ids=114843&ids=150894&ids=106961&ids=41901&ids=35387&ids=47610&ids=30432&ids=104820&ids=47395&ids=135999&ids=110294&ids=121094&ids=31385&ids=18472&ids=127869&ids=48589&ids=22612&ids=4985&ids=127472&ids=19980&ids=79774&ids=114465&ids=52603&ids=84900&ids=54925&ids=16312&ids=75254&ids=124454&ids=99875&ids=82302&ids=6371&ids=43820&ids=77993&ids=49951&ids=19618&ids=119790&ids=19166&ids=108077&ids=21957&ids=122539&ids=114758&ids=66649&ids=37030&ids=28067&ids=105123&ids=93975&ids=116969&ids=72982&ids=31756&ids=113825&ids=113047&ids=27603&ids=20026&ids=113866&ids=102500&ids=100873&ids=63517&ids=122738&ids=75195&ids=49110&ids=56025&ids=12621&ids=138561&ids=58891&ids=126023&ids=70866&ids=74119&ids=62423&ids=129595&ids=86628&ids=114539&ids=113207&ids=19125&ids=141169&ids=104185&ids=90972&ids=106854&ids=88132&ids=48188&ids=117647&ids=116984&ids=87635&ids=67132&ids=30298&ids=36958&ids=70400&ids=71065&ids=114431&ids=59740&ids=122279&ids=6976&ids=134613&ids=127567&ids=34431&ids=128965&ids=105231&ids=32497&ids=10770&ids=102498&ids=45382&ids=33514&ids=88281&ids=45756&ids=49597&ids=16880&ids=57718&ids=11989&ids=115021&ids=21287&ids=23979&ids=119814&ids=11537&ids=29158&ids=23152&ids=126259&ids=54309&ids=128675&ids=9272&ids=128967&ids=25980&ids=85627&ids=116297&ids=39424&ids=102580&ids=42901&ids=109963&ids=130243&ids=9727&ids=149462&ids=113719&ids=49008&ids=102505&ids=80634&ids=9295&ids=54079&ids=72276&ids=93258&ids=14292&ids=106628&ids=67122&ids=102123&ids=129003&ids=49442&ids=154317&ids=36056&ids=53279&ids=10185&ids=91504&ids=44447&ids=156312&ids=80848&ids=118775&ids=20103&ids=113801&ids=24083&ids=51388&ids=26116&ids=117844&ids=14674&ids=49860&ids=155300&ids=39091&ids=134513&ids=79715&ids=7692&ids=8328&ids=114306&ids=26073&ids=39108&ids=9927&ids=36819&ids=120646&ids=116274&ids=87150&ids=130764&ids=19323&ids=20781&ids=53557&ids=104971&ids=114315&ids=113842&ids=37424&ids=154971&ids=41377&ids=18741&ids=11669&ids=110244&ids=122200&ids=114460&ids=156623&ids=92932&ids=122536&ids=121683&ids=117994&ids=19569&ids=21856&ids=43727&ids=20669&ids=124089&ids=46823&ids=18381&ids=125302&ids=10676&ids=14661&ids=134298&ids=93045
```

**Comment by BlafKing** [comment] 2023-10-05 22:48
Unfortunately it's a bit more tricky to implement this than I anticipated, since API request handles the paging system and it breaks if multiple API requests are used.

All IDs are provided to the API in a single request, which then divides it into multiple pages based on the current tile count, if 2 API requests are delivered, then the divided pages won't match up, since there will be multiple pages with the same ID, and they don't redirect to each other.

A fix for this is to use custom paging metadata creation, I'll try to make code which modifies the metadata return of the API to create custom pages combined with the correct URL.

It will take a while to implement but I'll try to make it work :)

**Comment by BlafKing** [comment] 2023-10-06 02:57
I've successfully implemented custom page creation in update v1.14.2, which should fix your error.
I couldn't properly test it since I don't have enough models for it, but as far as I can tell it should all work well, was a fun challenge to get working 😄 

Please let me know if this solution works for you or if you're still experiencing issues! :)

**Comment by mosherc** [comment] 2023-10-06 03:25
Tested it out and it works perfectly, I am able to see updates for all my loras. Thanks!

**Comment by BlafKing** [comment] 2023-10-06 03:28
Awesome! Glad to hear that it's working well :)

I'll close this thread now since the issue is resolved 👍🏻

**Closed** 2023-10-06 03:28 UTC
Labels: bug, WIP
