### ISSUE TITLE
[Bug]: Cannot download anything.

### ISSUE THREAD

**Issue by Abishai2007** [BlafKing/sd-civitai-browser-plus#94] opened 2023-11-05 16:22 UTC
### Describe the bug.

Try to download anything from CivitAi and I get this error (example):
Error occured during download of "C:\SD\stable-diffusion-webui\models\Stable-diffusion\15\epicrealism_naturalSinRC1VAE.safetensors".
failed to read: "absolutereality_v181.cm-info.json": local variable 'sha256' referenced before assignment

### Steps to reproduce the problem.

1. Go to Select anuthing to download
2. Press Download
3. Does not download, but receive error instead

### Expected behavior

It should download the requested files.

### System info

* Extension version: 190f8485
* OS: Windows 11
* SD-WebUI version: 1.6.0
* Python: 3.10.11

### Console logs

```Shell
...
failed to read: "windyupskirt_SDXL.json": local variable 'sha256' referenced before assignment
failed to read: "xl_crystalline_dress-1.0.cm-info.json": local variable 'sha256' referenced before assignment
failed to read: "absolutereality_v181.cm-info.json": local variable 'sha256' referenced before assignment
failed to read: "absolutereality_v181.cm-info.json": local variable 'sha256' referenced before assignment
Error occured during download of "C:\SD\stable-diffusion-webui\models\Stable-diffusion\15\epicrealism_naturalSinRC1VAE.safetensors".
failed to read: "absolutereality_v181.cm-info.json": local variable 'sha256' referenced before assignment
```

### Additional information

I have Aria2 as the downloader.

**Comment by BlafKing** [comment] 2023-11-08 14:59
Sorry to hear you're experiencing issues!
I assume this is caused by the errors around it which are the sha256 errors, I see now that the code still attempts to read sha256 values even if any .json files do not contain them, I hope to post a fix for this somewhere today included in an update! :)

If the update does not fix your issue, then it would be helpful if you could turn on the "Show Aria2 logs in CMD" setting.
You can find this in SD-WebUI by going to `Settings > CivitAI Browser+`

**Comment by BlafKing** [comment] 2023-11-09 01:00
I've published an update which should hopefully solve this issue, please let me know if you're still experiencing it!
If not, please provide the Aria2 logs by enabling it in the CivitAI Browser settings tab.

**Comment by BlafKing** [comment] 2023-11-22 02:59
Since there has been no update in 2 weeks, I will close this issue.

If you're still experiencing the issue please feel free to send another message here and I'll make sure to further look into your issue! :)

**Closed by BlafKing** 2023-11-22 02:59 UTC
Labels: bug, WIP

**Comment by Tijgerd** [comment] 2023-11-22 10:09
this was also a bug for me, disabling Aria2 solved the issue but if you realy need it I can try to produce the log file.
On reddit and other platforms I can see posts with people having the same issues.
