### ISSUE TITLE
[Bug]: Filter->Click 'Save setting as default' button - json.decoder.JSONDecodeError: Expecting ':' delimiter: line 4964 column 5 (char 303142)

### ISSUE THREAD

**Issue by illuculent** [BlafKing/sd-civitai-browser-plus#75] opened 2023-10-15 09:51 UTC
### Describe the bug.

Won't save json and popup will not go away.

### Steps to reproduce the problem.

1. Go to Civit AI tab
2. Filter
3. Click 'Save setting as default' button
Error and popup won't go away.

### Expected behavior

Save json file

### System info

* Extension version: [2b64e96c](https://github.com/BlafKing/sd-civitai-browser-plus/commit/2b64e96c526837fcb6d8c815223aeb099224bc77)
* OS: Windows 11
* SD-WebUI version: 1.6.0
* Python: 3.10.11

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion\Packages\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 73, in saveSettings
    data = json.load(file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 4964 column 5 (char 303142)
```

**Comment by BlafKing** [comment] 2023-10-15 09:58
This issue is caused by a broken ui-config.json file,
You can find the file at: `webui/ui-config.json`
You can either manually try to repair the syntax of the file, or you can simply delete and restart SD-WebUI, which will then re-create the file and reset your saved settings.

This should fix this error, I unfortunately cannot make the extension fix this file.

**Comment by BlafKing** [comment] 2023-10-16 15:20
I'll close this thread since your issue should be solved by doing the steps mentioned above, if that didn't work please feel free to send another message in this thread!

**Closed by BlafKing** 2023-10-16 15:20 UTC
Labels: bug
