### ISSUE TITLE
[BUG] Installed folder location not updating properly when clicking on downloaded model

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#38] opened 2023-09-21 18:46 UTC
**Describe the bug**
Downloaded models now show the current folder as the bottom one in the dropdown.

**To Reproduce**
1. Click on thumbnail of model that has been downloaded, or download a model, then click the thumbnail again afterward.
2. Sub Folder displays as last one in the dropdown (presumably, as it always displays "vehicles" for me, as seen below).
3. It also will download to that folder if not changed before downloading new version of model.

**Expected behavior**
It should display the actual folder it's in, as before.

**Screenshots**
<img width="166" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/b7fce963-2736-47c4-a1b2-922f88716f5b">

**Comment by BlafKing** [comment] 2023-09-21 19:14
Not exactly sure how this is a bug?
It already displays the actual folder it's in as the default option, and the list is sorted alphabetically, here Detail tweaker model is in folder 'a' for example:
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/e8f96129-1004-4c27-9c37-6fd2069e4ddc)

The other 2 options (being the model name and model name+version name) are always inserted as the first 2 options for users that want to use this name sequencing.

The only change I could make is not automatically using the same folder when selecting another version but I personally wouldn't find that useful since it's a good assumption to make that another version of the same model should be put in the same sub folder by default.

**Comment by BlafKing** [comment] 2023-09-21 20:11
I've just published an update that adds an option to disable inserting the 2 default sub folders just in case you'd be interested in doing so, the rest is intended behaviour so I'll close this bug thread since it's not a bug.

**Comment by ManOrMonster** [comment] 2023-09-21 20:58
> Not exactly sure how this is a bug? It already displays the actual folder it's in as the default option, and the list is sorted alphabetically

That's my report, that it is **not showing** the actual folder it's installed in. I just noticed this new behavior today.

Starting today, it always shows it's in the vehicles folder, even though none of the models are in that folder. "Vehicles" just happens to be at the bottom of the list alphabetically, and for some reason it's picking that.

I just did a test and made a new folder called "x" but its still picking "vehicles" no matter which downloaded model I click on. What the heck could be causing that?

I did have a peculiar incident this morning, but it resolved itself soon after, and I've had this issue since. But I don't know if it was caused by that. I noticed I could now select LORA and LoCon at once, so I tried that out, but when I clicked on a LoCon, the default download folder reverted to lycoris instead of lora. I was going to put in a bug report but then I couldn't replicate it after that. Maybe this is somehow related? Is there a cache somewhere that needs to be trashed?

I also did a "Load all installed models" yesterday which eventually errored out. I see updated JSON files from yesterday in the vehicles folder, but they're just associated with the five models in that folder. Could that have messed something up?

**Comment by ManOrMonster** [comment] 2023-09-21 21:17
Another thing I jsut noticed, it's Lora and LoCon doing this. Checkpoints are showing the correct folder. I should also note that all of my Lora folder names have a period in front of them, not that it should matter.

**Comment by BlafKing** [comment] 2023-09-21 21:22
Thanks for the extra info! And apologies for misreading/misunderstanding your initial bug report.

This extra info will help to debug what's causing this issue.

(I suspect it has something to do with the new sha256 version installed status detection)

I'll have a look into what could be causing it tomorrow since I'll have to head to bed soon :') 👍🏻

**Comment by BlafKing** [comment] 2023-09-22 10:16
I'm having trouble recreating the issue so it's hard for me to bug test.
If you could provide it, some additional info would help:
> That's my report, that it is not showing the actual folder it's installed in.

To be clear, are the folders showing up at all? or are they missing from the list?
Or is the issue that the folders do show up but the correct one isn't selected by default?

Also:
In the "Download Folder:" Textbox, does the folder correctly show up there when selecting a downloaded model? or is it also the incorrect folder?

also quick fyi, I've made a quick update which has now added a toggle in the settings for placing LoCon's in the LORA folder, I remember you had all your LoCon's in the LORA folder so make sure to toggle that off in the latest update :)

(I've done this since the version check fails on programs like SD Next so users that use that can now toggle it instead of it being version dependant)

**Comment by ManOrMonster** [comment] 2023-09-22 17:49
> To be clear, are the folders showing up at all? or are they missing from the list? Or is the issue that the folders do show up but the correct one isn't selected by default?

They are all there. The issue is that it does not select the correct one, but rather "\.vehicles" every time.

As you can see here, I have "Weird Dog" downloaded, but it is not in "\.vehicles", it's actually in "\.meme". Yet is shows as being in "\.vehicles".

<img width="563" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/5968ef31-47df-4cab-b329-384a2d3fd695">

This is true for every single LORA/LoCon, including one I just downloaded. On a newly downloaded one, I just click the thumbnail again, and it's back to ".vehicles", even though it's not in there.

I have 30 folders in my Lora folder. They all appear in the dropdown.

<details><summary>Click here for a step-by-step demo of this happening after downloading a new model...</summary>

<h3>Click thumbnail, all looks good:</h3>

<img width="573" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/f88f018d-4330-4f5a-a9a6-8ffd11e723f4">


<h3>Choose ".concepts" as destination:</h3>

<img width="587" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/0f305e37-c2c5-4ad1-a042-f40647d023f1">


<h3>Download model:</h3>

<img width="584" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/3b388b58-40d6-4874-82dd-598f54199286">


<h3>After downloading, everything is still right:</h3>

<img width="567" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/7568affa-75c9-4794-8453-f41c78e96f64">

<h3>Click the thumbnail again, aaaaaand... now it's showing ".vehicles":</h3>

<img width="581" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/db0249c2-838e-4373-884c-c6d1de9287b4">

<h3>But it's actually under ".concepts":</h3>

<img width="362" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/fd33b3d8-1085-4c6b-bdd7-454460b2bd12">

</details> 

> Also: In the "Download Folder:" Textbox, does the folder correctly show up there when selecting a downloaded model? or is it also the incorrect folder?

It looks like this when clicking on a downloaded model:

<img width="274" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/5b0c8037-4066-427a-9df9-3c26d9d57f40">

FYI, my models folder is a symlink to a different folder that is not actually located under my automatic1111 install. That shouldn't be an issue though.

I thought I might have inadvertently set a default to ".vehicles" in a1111 settings, but I thoroughly checked ui-config.json, didn't see anything in there.

> also quick fyi, I've made a quick update which has now added a toggle in the settings for placing LoCon's in the LORA folder, I remember you had all your LoCon's in the LORA folder so make sure to toggle that off in the latest update :)

I figured this was coming eventually, thanks for adding the setting!

**Comment by BlafKing** [comment] 2023-09-23 09:56
Thanks for taking the time to write such a detailed bug description! I've now managed to re-create the error so it's time for debugging :)

**Comment by BlafKing** [comment] 2023-09-23 11:37
The issue is now fixed!
It was indeed caused by the sha256 value checking which I implemented in completely the wrong way, thanks for pointing out the issue and making such detailed error descriptions!

I'll close this thread now since the bug should be fixed! :)

**Closed by BlafKing** 2023-09-23 11:37 UTC
Labels: bug, WIP

**Comment by BlafKing** [comment] 2023-09-23 12:04
The previous fix broke loading the model page, so I've made a temp fix which removes checking for sha256 while fetching available versions, I'll publish a proper fix for this in a bit!
