### ISSUE TITLE
[Bug]: After Downloading new version, File name becomes the new version no matter the option chosen

### ISSUE THREAD

**Issue by gurukast** [BlafKing/sd-civitai-browser-plus#82] opened 2023-10-22 21:50 UTC
### Describe the bug.

![pruned-download](https://github.com/BlafKing/sd-civitai-browser-plus/assets/132414857/d2a0f531-629c-414e-9abc-fd5c5fc64e1b)
![full download](https://github.com/BlafKing/sd-civitai-browser-plus/assets/132414857/d9d1edb8-ac66-499a-b678-51e834e6667e)

Was attempting to switch from a full model, to a pruned model. but wanted to download the pruned model first, before deleting the old model.  After downloading, switching between the pruned and the full  version, did not change the file name.
Full name should be : dreamscapesDragonfireNEW_dsDv20
Pruned Name is        : dreamscapesDragonfireNEWV20_dsDv20

### Steps to reproduce the problem.

1. Go to Model version
2. choose "pruned version"
3. Downloaded
4. ...switch to "full version" to delete
5. notice file name is not changed.

### Expected behavior

matching file names to whats installed to deltele

### System info

v1.14.6 (Hotfix)
windows 10
version: [v1.6.0] •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  • 

### Console logs

```Shell
10/22 17:07:35 [NOTICE] Download complete: M:/AI/A160/stable-diffusion-webui/models/Stable-diffusion/Fantasy/dreamscapesDragonfireNEWV20_dsDv20.safetensors
Model saved to: M:\AI\A160\stable-diffusion-webui\models\Stable-diffusion\Fantasy\dreamscapesDragonfireNEWV20_dsDv20.safetensors
Tags saved to: M:\AI\A160\stable-diffusion-webui\models\Stable-diffusion\Fantasy\dreamscapesDragonfireNEWV20_dsDv20.json
Preview image saved to: M:\AI\A160\stable-diffusion-webui\models\Stable-diffusion\Fantasy\dreamscapesDragonfireNEWV20_dsDv20.preview.png
Error decoding JSON: 'NoneType' object has no attribute 'upper'
Error decoding JSON: 'NoneType' object has no attribute 'upper'
```

**Comment by BlafKing** [comment] 2023-10-22 23:10
The issue seems to be with CivitAI's API since it returns the same file name for both files
You can see the relevant return from the API in this dropdown:

<details>
<summary>API Return</summary>

```
"files": [
    {
        "id": 62518,
        "sizeKB": 5539815.23828125,
        "name": "dreamscapesDragonfireNEWV20_dsDv20.safetensors",
        "type": "Model",
        "metadata": {
            "fp": "fp16",
            "size": "full",
            "format": "SafeTensor"
        },
        "pickleScanResult": "Success",
        "pickleScanMessage": "No Pickle imports",
        "virusScanResult": "Success",
        "virusScanMessage": null,
        "scannedAt": "2023-06-07T04:36:33.424Z",
        "hashes": {
            "AutoV1": "FAA16408",
            "AutoV2": "64A21449D7",
            "SHA256": "64A21449D747FB5CC13672EDF220BA22C25EA80FB1AB1D55673E02E603C5B459",
            "CRC32": "7863AB54",
            "BLAKE3": "819984342AE5175835E16EACFF96476B251628FD79C745388C5013B11CFA061B"
        },
        "downloadUrl": "https://civitai.com/api/download/models/90587?type=Model&format=SafeTensor&size=full&fp=fp16"
    },
    {
        "id": 63233,
        "sizeKB": 2082667.150390625,
        "name": "dreamscapesDragonfireNEWV20_dsDv20.safetensors",
        "type": "Model",
        "metadata": {
            "fp": "fp16",
            "size": "pruned",
            "format": "SafeTensor"
        },
        "pickleScanResult": "Success",
        "pickleScanMessage": "No Pickle imports",
        "virusScanResult": "Success",
        "virusScanMessage": null,
        "scannedAt": "2023-06-08T14:06:54.050Z",
        "hashes": {
            "AutoV1": "050F0BAE",
            "AutoV2": "C15090D329",
            "SHA256": "C15090D32922378312166A543C971093AC66BA7503E663550EE00027BD769132",
            "CRC32": "B55881F8",
            "BLAKE3": "6E03690204AAA6F3D3B04E25E59B3AC7A3CB9C5944F4158B7DDA48AA74CE6D71"
        },
        "downloadUrl": "https://civitai.com/api/download/models/90587",
        "primary": true
    }
],
```
</details>

As you can see both of the `"name"` entries contain the same filename for each file, if you believe this is an error/bug you can report it as a bug to CivitAI [here](https://civitai.featurebase.app/)

The `Error decoding JSON: 'NoneType' object has no attribute 'upper'` shouldn't happen however and is caused by the extension, when did this error occur exactly?

**Comment by gurukast** [comment] 2023-10-23 06:18
> The issue seems to be with CivitAI's API since it returns the same file name for both files You can see the relevant return from the API in this dropdown:
> 
> API Return
> As you can see both of the `"name"` entries contain the same filename for each file, if you believe this is an error/bug you can report it as a bug to CivitAI [here](https://civitai.featurebase.app/)
> 
> The `Error decoding JSON: 'NoneType' object has no attribute 'upper'` shouldn't happen however and is caused by the extension, when did this error occur exactly?

right after downloading the  pruned version

**Comment by BlafKing** [comment] 2023-10-23 16:31
> right after downloading the pruned version

Thanks for the additional info, the NoneType error should now no longer occur, like I said I can however not do much about the filename 😅 

I'll close this issue since I cannot solve the issue in your main post.

**Closed by BlafKing** 2023-10-23 16:30 UTC
Labels: bug, cantfix
