### ISSUE TITLE
[Bug]: Search results are broken

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#235] opened 2024-03-17 02:39 UTC
### Describe the bug.

After the rewrite, search results in the extension are different from the civitai webiste. 

### Steps to reproduce the problem.

1. Set options the same as the screenshot below
2. Only 4 models show up
3. Set the same options on https://civitai.com/models
4. See all the missing models

![firefox_xDpOGbiybG](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/9c4376d2-888e-41ba-acb4-a1dc98c4d014)

![firefox_ralTObCa7H](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/7f4049a8-bc98-4324-aa77-337551a724bc)

### Expected behavior

Model results should match https://civitai.com/models

### System info

* Extension version: https://github.com/BlafKing/sd-civitai-browser-plus/commit/2db0fa857079ca1fde17352990e9484df202ff28
* OS: Win 11
* SD-WebUI version: 1.8
* Python: 3.10.6

### Console logs

```Shell
Not Applicable
```

**Comment by Terroosh** [comment] 2024-03-17 02:46
It looks like both the Base Model options and the Sort by date options are broken.

**Comment by BlafKing** [comment] 2024-03-17 02:47
Thanks for reporting!

I see now that I've made a mistake in how the basemodels parameter is created for the API Request URL.
I'll post a hotfix for this shortly!

**Comment by kyle215ps3** [comment] 2024-03-17 02:57
> Thanks for reporting!
> 
> I see now that I've made a mistake in how the basemodels and content type parameters are created for the API Request URL. I'll post a hotfix for this shortly!
> 
> This should also hopefully fix the sorting issue, as my extension cannot influence the sorting when all the parameters are correct.

hopefully it works for me, cause I get error all over the place even though I updated and got a new api xD

**Comment by BlafKing** [comment] 2024-03-17 02:59
> hopefully it works for me, cause I get error all over the place even though I updated and got a new api xD


I assume those are likely caused by the issue mentioned in #233
If so, then the issue unfortunately needs to be fixed by CivitAI, as there is currently a bug that returns internal server errors after a few pages with the latest version of their API.

**Comment by BlafKing** [comment] 2024-03-17 03:04
Latest commit should fix the issue mentioned in this post.

Thanks again for reporting! :)

**Closed by BlafKing** 2024-03-17 03:04 UTC
Labels: bug, WIP

**Comment by Terroosh** [comment] 2024-03-17 03:18
> Latest commit should fix the issue mentioned in this post.
> 
> Thanks again for reporting! :)

Sorting issue was also fixed with this update.
