### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jwvanderbeck** [BlafKing/sd-civitai-browser-plus#28] opened 2023-09-14 20:45 UTC
**Describe the bug**
I select a model card, and click Download Model.  The progress never advances past 0%

**To Reproduce**
1. Select the Civit AI Tab
2. Click Refresh
3. Select a model card
4. Click Download Model

**Expected behavior**
Model should download

**Screenshots**
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/161126/356c004b-ac6d-4142-9049-a5ade410bdc4)

**Additional context**
* Extension version: f9e980bd
* OS: OS (Windows/Linux Distro) Widnows 11
* SD version: A1111 version: Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
* Python: Not sure where to find this
* Any Additional info

**Comment by BlafKing** [comment] 2023-09-14 20:55
Hi there!
Could you open up the Settings tab then click the 'Civit AI' tile and turn on Aria2 logs?
This would help me identify the issue.

**Comment by jwvanderbeck** [comment] 2023-09-14 20:55
Sorry just saw there are some workarounds for this which I will try... Except for some reason now the button to Download Model is vanishing as soon as I select a model tile :(

**Comment by jwvanderbeck** [comment] 2023-09-14 20:56
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/161126/e96e2dc6-bc50-4330-a6f5-a33cf4e64052)
No "Download Model" button anymore? :(

**Comment by BlafKing** [comment] 2023-09-14 20:59
Have you restarted Automatic1111 Stable Diffusion?
I haven't experienced this error before.

Generally only users from Russia experience issues with using Aria2 for downloading.
You can try to turn on downloading with Aria2 and also turn on Aria2 logs and then fully restart Automatic1111 Stable Diffusion.

This should give me more insight in what's causing the error.

**Comment by jwvanderbeck** [comment] 2023-09-14 21:10
So this is the Civit AI log but nothing additional is spit out when I click Download.  Going to try the alternate download method.

Civitai Helper: Start scan_model
Civitai Helper: Scanning path: E:\stable-diffusion-webui\embeddings
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\Artgerm.bin
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\ArtgermStyle-neg.pt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\ArtgermStyle.pt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\bad-hands-5.pt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\HyperStylizeV6.pt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\embeddings\MakeItPopVA.pt
Civitai Helper: Model Info is empty
Civitai Helper: Scanning path: E:\stable-diffusion-webui\models\hypernetworks
Civitai Helper: Scanning path: E:\stable-diffusion-webui\models\Stable-diffusion
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\0.7(protogenX53Photorealism_10) + 0.3(rpg_V4).safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\hassanblend1512And_hassanblend1512.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\instruct-pix2pix-00-22000.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\last.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\modelshoot-1.0.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Creating model info for: reliberate_v10.safetensors
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: 980cb713af26d3f34968857e60d15085b1988bc44d3056f8c1f6c5893dcf24f3
Civitai Helper: length: 2132625894
Civitai Helper: Request model info from civitai
Civitai Helper: Write model info to file: E:\stable-diffusion-webui\models\Stable-diffusion\reliberate_v10.civitai.info
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\reliberate_v10.safetensors
Civitai Helper: This image is NSFW
Civitai Helper: Downloading file from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/6b1e31ac-3ec0-46ee-a31e-34341e051849/width=1280/991070.jpeg
Civitai Helper: File downloaded to: E:\stable-diffusion-webui\models\Stable-diffusion\reliberate_v10.preview.png
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\RPG Inpunk 0.7M.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\RPG Stylized.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.1(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(xperoEnd1essModel_v1 - SD-mode-1.5l).ckpt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.4(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l).safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\SD-mode-1.5l.ckpt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\SD-model-1.4.ckpt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\sd-v1-5-inpainting.ckpt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Stable-diffusion\v2-1_768-ema-pruned.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Scanning path: E:\stable-diffusion-webui\models\Lora
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Lora\artgerm.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Lora\ayonimixV3Lora300_ayonimixV3Lora300.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Lora\comicdiffusion_Lora300.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Lora\dreamshaperLora300_dreamshaperLora300.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\stable-diffusion-webui\models\Lora\duskfallsIllustration_duskfallsIllustration.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Done. Scanned 74 models, checked 74 images

**Comment by BlafKing** [comment] 2023-09-15 01:34
Since I assume you're not from Russia, downloading using Aria2 should also work for you.
I assume the error is caused by Aria2 not starting up.

The extension defines the install location based on the OS that's being used.
I'm not exactly sure what "`OS (Windows/Linux Distro) Windows 11`" is but I assume that means you're using Linux on Windows?

The issue might reside there, The extension might need to use Aria2 for Linux but is detecting your OS as Windows and is thus trying to use the windows version of Aria2.

I've added an extra check in v1.10.1 that will attempt to start the Linux version if no RPC server has been successfully started!

I'll close this thread now since your issue should be solved either by the extra check, or the issue lies elsewhere which I cannot find and you should use the old_download method instead to fix it.

Thanks for reporting the issue! :)

**Closed by BlafKing** 2023-09-15 01:34 UTC
Labels: bug

**Comment by jwvanderbeck** [comment] 2023-09-15 02:40
> I'm not exactly sure what "OS (Windows/Linux Distro) Windows 11" is but I assume that means you're using Linux on Windows?
No I am just on Windows 11.  I apparently didn't edit the template properly that's all.

I am also not in Russia.  I am in the USA.

**Comment by BlafKing** [comment] 2023-09-15 10:56
Ah I see, I'm unfortunately not sure what else could be causing the issue then, glad to hear the old download method is working though :)
