### ISSUE TITLE
[Bug]: Load installed models - List index out of range

### ISSUE THREAD

**Issue by Zaazu** [BlafKing/sd-civitai-browser-plus#80] opened 2023-10-22 08:56 UTC
### Describe the bug.

Clicking on Load installed models causes a list index out of range error. The button then becomes stuck on "Cancel loading".

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/22891753/c06ce64f-f50f-4c0a-a965-404f7f583f25)

### Steps to reproduce the problem.

1. Go to "Civitai" tab
2. Press "Update Models"
3. Press "Load installed models"

### Expected behavior

Installed models should load

### System info

* Extension version: 90479004
* OS: Windows 11 Pro Version 22H2 (OS Build 22621.2428)
* SD-WebUI version: v1.6.0  5ef669de080814067961f28357256e8fe27544f4
* Python: 3.10.6

### Console logs

```Shell
venv "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements for CivitAI Browser
Launching Web UI with arguments: --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast --ckpt-dir ..\..\Models\Stable-diffusion --vae-dir ..\..\Models\VAE --lora-dir ..\..\Models\Lora --embeddings-dir ..\..\Models\Embeddings --esrgan-models-path ..\..\Models\ESRGAN --realesrgan-models-path ..\..\Models\RealESRGAN
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Aria2 RPC started
2023-10-22 09:46:15,704 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-22 09:46:15,795 - ControlNet - INFO - ControlNet v1.1.411
Loading weights [e247d28b0a] from ..\..\Models\Stable-diffusion\SDXL\fenrisxl_v1003Photorealistic.safetensors
Creating model from config: D:\Software\StableDiffusion\A1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: sdp-no-mem... done.
Model loaded in 3.5s (load weights from disk: 0.8s, create model: 0.3s, apply weights to model: 2.1s, calculate empty prompt: 0.1s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 18.9s (prepare environment: 4.7s, import torch: 2.1s, import gradio: 0.6s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 5.9s, create ui: 4.2s, gradio launch: 0.1s).
Traceback (most recent call last):
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 536, in file_scan
    if progress:
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 505, in __len__
    return self.iterables[-1].length
IndexError: list index out of range
```

**Comment by BlafKing** [comment] 2023-10-22 13:26
This issue is caused by the latest hotfix, thx for reporting it!

I've published another hotfix that should fix this issue, please let me know if you're still experiencing it! :)

**Comment by BlafKing** [comment] 2023-10-24 19:40
I'll close this issue since it should be solved, feel free to send another message here if the issue still persists 👍🏻

**Closed by BlafKing** 2023-10-24 19:40 UTC
Labels: bug, WIP
