### ISSUE TITLE
[Bug]: Some models attempt to download the wrong file which inturrupts queue

### ISSUE THREAD

**Issue by Vesperindustrial** [BlafKing/sd-civitai-browser-plus#180] opened 2024-01-28 20:59 UTC
### Describe the bug.

With lora https://civitai.com/models/273898 but happens on others, using the checkbox to add to the batch download queue, it appears to attempt to download a training data zip file which may or may not actually exist. Once this occurs it will then fail and seemingly interrupt the remainder of the queued downloads if there are any. Downloading using the one-at-a-time download model button for individual downloading works correctly.

EDIT: Doesn't seem to always fail the rest of the queue, but seems inconsistent whether or not it occurs

### Steps to reproduce the problem.

1. Go to https://civitai.com/models/273898
2. Press checkbox to add to batch download
3. Download will fail with the console logs provided in the following section
4. any existing download queue will silently stop

### Expected behavior

It shouldn't be downloading the training data, and/or there should be some kind of notification and should instead download the safetensors lora.

### System info

* Extension version: 9e70db57
* OS: Windows 10
* SD-WebUI version: a1111 1.7.0

### Console logs

```Shell
CivitAI Browser+: File: "308707_training_data.zip" not found on CivitAI servers, it looks like the file is not available for download.
CivitAI Browser+: Error occured during download of "308707_training_data.zip"
```

**Comment by BlafKing** [comment] 2024-02-06 12:55
Thanks for reporting!

This ended up being caused by the the default file not getting properly assigned when multi downloading was used, which should now be fixed, I've also tried to implement a way to handle download failures better, but I'm still testing that so there might still be some issues, please feel free to post another message here if you encounter any more issues with it!

The errors should now be fixed in the latest version! :)

**Closed by BlafKing** 2024-02-06 12:55 UTC
Labels: bug
