### ISSUE TITLE
[Bug]: Civit-API has timed out

### ISSUE THREAD

**Issue by dowier** [BlafKing/sd-civitai-browser-plus#110] opened 2023-11-24 14:32 UTC
### Describe the bug.

No matter what keyword you search for, it always reports a timeout, even with VPN turned on

### Steps to reproduce the problem.

1. search anthing key words

### Expected behavior

Ability to display search results

### System info

* Extension version:[ef12ec84]
* OS:win10
* SD-WebUI version:1.6.1
* Python:3.10.11

### Console logs

```Shell
CivitAI Browser+: Error: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/models?limit=15&page=1&sort=Most%20Downloaded&period=AllTime&query=angthing&nsfw=false (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019F3B4EB2E0>, 'Connection to civitai.com timed out. (connect timeout=10)'))
```

### Additional information

I can access the civitai website normally with VPN on, but not with this plugin, I don't know why.

**Comment by BlafKing** [comment] 2023-11-26 17:37
I'm not exactly sure what could cause this to happen, looks like Cloudflare is blocking requests from your location.

Also, the CivitAI site uses a different API than the public one, so that's why it could be possible for you to visit using the site, but not in this tool, the one they use isn't accessible to the public.

It's hard for me to figure out what the issue could be, since I cannot recreate the issue, I've attempted to fix it by adding some headers to the requests in the latest update [v2.0.1](https://github.com/BlafKing/sd-civitai-browser-plus/commit/95f6d8e45f6bfd45feb4010625844500685eadad)

You can try to see if that helps fix your issue, if not, then I unfortunately don't know much else that I can do in the extension itself.

**Comment by Terroosh** [comment] 2023-11-26 18:52
Got the same error today. Updating to 2.0.1 fixed it.

**Comment by BlafKing** [comment] 2023-11-27 17:35
That was likely caused by CivitAI, and not this update 😅

If you're receiving a "Read timeout" then the issue is likely on CivitAI's end, since that means that you're able to connect to the server but you're not receiving any return, this likely indicates that there's either high traffic, or server issues.

If you're getting a "Connect timeout" however, then this means that you're unable to connect to CivitAI at all, so this suggests that the issue is on the users end, or it's caused by being blocked from connecting/reaching the server by something like Cloudflare.

**Comment by Terroosh** [comment] 2023-11-27 18:47
> That was likely caused by CivitAI, and not this update 😅
> 
> If you're receiving a "Read timeout" then the issue is likely on CivitAI's end, since that means that you're able to connect to the server but you're not receiving any return, this likely indicates that there's either high traffic, or server issues.
> 
> If you're getting a "Connect timeout" however, then this means that you're unable to connect to CivitAI at all, so this suggests that the issue is on the users end, or it's caused by being blocked from connecting/reaching the server by something like Cloudflare.

All I can say is that I kept getting that error and restarting the webui didn't work so I looked at the issues list and saw this post and that you put out a new update with headers. Right after updating it worked like usual. Whatever the cause was, the headers you added fixed it.

**Comment by BlafKing** [comment] 2023-12-05 18:41
Since there haven't been any updates for a while in this bug report, I'll go ahead and close it.

If you're still experiencing issues, please feel free to send another message here and I'll look into if there's anything I can do to help fix the issue!

**Closed by BlafKing** 2023-12-05 18:41 UTC
Labels: bug
