### ISSUE TITLE
Only one file per "Version" can be installed

### ISSUE THREAD

**Issue by loban4** [BlafKing/sd-civitai-browser-plus#40] opened 2023-09-22 10:47 UTC
**Describe the bug**
For some Datasets/Tools, multiple files are required. My particular problem is with the ControlNet https://civitai.com/models/38784?modelVersionId=67566  
Those need the *.safetensor and the .yaml file to run.
When downloading either one of these files the "Version" is shown as installed and no other files can be downloaded for it.

**To Reproduce**
1. Go to CivitAI Tab and search for "ControlNet 1.1" (Tyoe Controlnet)
2. Select "Controlnet 1.1 Models", Version "Depth" (for example)
3. Select the "safetensor" file (name show as Model Filename is *.safetensor") and install
4. Wait for installation to finish
5. Select the "other" file  (name show as Model Filename is still *.safetensor")
6. Download Button is still "Delete Model"

Alternative Way:
1. Download the .YAML File from Civit AI directly
2. Paste it into the respective folder (Default".\models\ControlNet\"
3. Check the model in the Civit AI Tab
4. Model shows as "installed"

**Expected behavior**
When selecting the other file delete should show as "download"
When selecting the other file the name in Model Filename should have the correct suffix

**Screenshots**

**Additional context**
* Extension version: v1.11 (apparently based on [v1.1.0] from SignalFlagZ), checking the repo from SignalFlagZ there seem to be a lot of fixes since 1.1.0, also regarding file naming.
* 
* OS: OS Windows 10
* SD version: A1111 version [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)
* Python: version:  python: 3.10.6 

* Any Additional info
That would be a future request, but for these kind of downloads a "Download all Files" as well as a "Download all Version"/"Download all Versions with all Files" option would be really helpfull.

**Comment by BlafKing** [comment] 2023-09-22 13:24
Solid reqeust, I'll see if I can find a good way to implement this.

> When selecting the other file the name in Model Filename should have the correct suffix

I currently can't recreate an error where the wrong suffix is displayed (I'm assuming you mean extension, .safetensor, .yaml etc.)
Please make sure you're using the latest version since I've modified the code that shows the filename since 1.11 so that should be fixed already or caused by something I can't seem to recreate, please let me know if it's fixed in the latest version or if you intended to refer to something else.
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/2836692a-1fd8-4e6e-a60f-296244eead82)
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/553da1ed-980b-49bb-9fed-cf44ff9c936d)


> checking the repo from SignalFlagZ there seem to be a lot of fixes since 1.1.0, also regarding file naming.

Fixes in SignlFlagZ repo aren't relevant for this extension since they differ a lot by now.
My 1.0 version is created from SignalFlagZ's 1.1.0 but as you can see by the changelog of this extension, they differ a lot by now so merging any fixes he has applied to this extension isn't really a feasible solution imo.
(The filename issue should already be fixed though as far as I can tell)

> For these kind of downloads a "Download all Files" as well as a "Download all Version"/"Download all Versions with all Files" option would be really helpfull.

This would require a download queue, which in theory would be possible, but isn't something that I can feasibly implement with my python skils :,)
I'll look into the possibility of doing so though since it should be easier now that Aria2 handles downloads.

Other than that, I'll start working on enabling the download button on a per file basis 👍🏻

**Comment by BlafKing** [comment] 2023-09-23 22:14
This feature/bug fix has now been implemented in v1.12.2, I'll close this thread now since the requested fix has been implemented! :)

**Closed by BlafKing** 2023-09-23 22:14 UTC
Labels: enhancement, WIP
