### ISSUE TITLE
[Bug]: AttributeError: 'Textbox' object has no attribute 'input'

### ISSUE THREAD

**Issue by BoozyAF** [BlafKing/sd-civitai-browser-plus#73] opened 2023-10-14 11:39 UTC
### Describe the bug.

After installing and reloading to apply, the extension does not come up in the navigation tab and gives an error in the console

### Steps to reproduce the problem.

1. Install the extension from the webui
2. Apply and reload extensions

### Expected behavior

Should load and work as normal

### System info

* Extension version: 2b64e96c
* OS: Windows 11
* SD-WebUI version: v1.2.1
* Python: 3.10.6

### Console logs

```Shell
File "E:\xxx\xxx\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 277, in on_ui_tabs
    trained_tags.input(
AttributeError: 'Textbox' object has no attribute 'input'
```

### Additional information

Almost no custom extensions or settings have been added/changed in the webui

**Comment by BlafKing** [comment] 2023-10-14 11:42
I assume this error is caused by an outdated version of WebUI (you wrote that you have v1.2.1 latest is v1.6.0), could you try updating your WebUI to see if this helps solve the issue?

**Comment by BoozyAF** [comment] 2023-10-14 11:51
> I assume this error is caused by an outdated version of WebUI (you wrote that you have v1.2.1 latest is v1.6.0), could you try updating your WebUI to see if this helps solve the issue?
> 
> I'll also look into the possibility to further compatibility with older versions! :)

That did seem to fix it, sorry about this, forgot to check the version.

**Comment by BlafKing** [comment] 2023-10-14 11:52
All good, no worries!
Glad to hear that solved the issue :)

I'll close this thread since the issue is resolved 👍🏻

**Closed** 2023-10-14 11:53 UTC
Labels: bug
