### ISSUE TITLE
[Bug]: Page jump not working

### ISSUE THREAD

**Issue by ArchAngelAries** [BlafKing/sd-civitai-browser-plus#311] opened 2024-07-13 01:13 UTC
### Describe the bug.

I'm not sure when it happened but it's been like this for a while. I'll use the extension as normal, but I can no longer manually enter the page I was on previously and hit enter and be taken to that page again. Also the same is true for the page up and down arrows and page seek bar. With the page seek bar, I can go backwards, but not forwards again. No errors are present in console when this takes place, and these are consistent.

### Steps to reproduce the problem.

1. Not sure if it's reproduceable, but... Go to extension, begin browsing
2. try to manually jump page to number or change page number via the arrows
3. It loads/refreshes the search, but doesn't take you to the page you want

### Expected behavior

It used to allow page jump to manually inputted pages and scrolling back and forth between loaded pages. Just kinda expected these features to remain.

### System info

* Extension version: 0b97a482
* OS: Win 11
* SD-WebUI version: A1111 directml/zluda ee49046780939fd8ee9c8e83d040203da4090ff3
* Python: 3.10.6

### Console logs

```Shell
N/A - No error messages appear
```

### Additional information

I really love your extension, and am so thankful for your hard work! I hope these issues can be fixed.

**Comment by BlafKing** [comment] 2024-10-10 21:26
Unfortunately not a bug, but intended behaviour.
This has to do with the new paging system of the API of CivitAI, before pages used to be indexed, so that you could jump to a specific page, but with the "new" API of CivitAI, this is unfortunately no longer possible, a page can only be jumped to after it's been visited.

Not really anything I can do about it :,)
I'll close this and mark it as not a bug

**Closed by BlafKing** 2024-10-10 21:26 UTC
Labels: bug
