### ISSUE TITLE
[BUG] Clicking on a different thumbnail during model download sometimes causes model info page to not load.

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#13] opened 2023-09-04 20:05 UTC
**Describe the bug**
While downloading a model, if clicking on a thumbnail to load a different model info page, that model info page _may_ sit there loading indefinitely without timing out.. This usually happens when Civitai is overloaded.

The only resolution that I've found is to refresh the auto1111 page. Using the "Refresh" button, changing pages, clicking on a different thumbnail, nothing resets it besides refreshing the page.

**To Reproduce**
1. Download a model.
2. While downloading, click on a different thumbnail.
3. The model page will sit there loading indefinitely. Does not happen every time.

**Expected behavior**
The model info page should either time out or load eventually.

**Potential solution**
Successfully downloading a model could trigger a refresh of the currenty displayed model info page? Or maybe a Retry button of some kind that stops the attempt to load the data and reloads it.

**Comment by BlafKing** [comment] 2023-09-05 04:36
Mhm that's an odd error, I'm not exactly sure what could be causing it since it cannot be caused by CivitAI timing out when selecting a tile.

When you press Refresh, Next Page or Prev Page all relevent data of the loaded tiles gets loaded into 'json_data'
Selecting a tile only sorts this data for the relevant tile and presents it to the user, it doesn't make any requests to CivitAI and thus it has no way to time-out so there must be something else breaking.

If there are any error logs in the cmd when this occurs then it would be helpful if you could provide those!
I'll need to do some further bug testing to see why this issue occurs since I currently can't seem to re-create it.

**Comment by ManOrMonster** [comment] 2023-09-05 05:50
I haven't noticed any messages in the console appear when it happens, but I'll keep an eye out. I'm probably always using my tablet when this happens, and other weird infinite loading things happen when I'm using it also. For instance, sometimes it will sit there showing that it's loading the checkpoint infinitely, but I can still generate images. Might not actually be an issue with your extension, just a general issue with Gradio.

**Comment by BlafKing** [comment] 2023-09-05 08:42
That does unfortunately sound like a gradio issue or A1111 issue, especially since the only solution is reloading the entire page.
A good indicator that it's not an issue caused by an extension is the lack of an error log, usually if an extension breaks to the point where basically nothing works anymore then an error log is expected.

I'll close this bug report for now unless I find some more info regarding the issues your facing, feel free to send a message here anytime and I'll look into it further!

**Closed by BlafKing** 2023-09-05 08:42 UTC
Labels: bug
