### ISSUE TITLE
[Bug]: 'Save model info' broken. HTML file is created in wrong location. New "auto save" options ignores custom save images location.

### ISSUE THREAD

**Issue by hakaserver** [BlafKing/sd-civitai-browser-plus#193] opened 2024-02-09 04:44 UTC
### Describe the bug.

After updating to the latest commit I noticed lots of new bugs when downloading model info and image samples. It may have been introduced with the implementation of the two new 'auto download' options. The list of bugs and/or behaviour changes (compared to the previous commit) are as described below.

### Steps to reproduce the problem.

After updating to the latest commit:

**With both new options _DISABLED_ and a custom image save location set:**

- 'Save model info' does not work and gives an error message (full error message in the 'console log' section).
- 'Save images' downloads sample images correctly but no longer saves the .html file and .civitai.info (now renamed to .api_info.json?). It used to download both files to the 'custom image save location'.
- 'Save images' now downloads the .preview.png file to the 'model download location' ahead of time.
- 'Download model' continues saving the .safetensors, .json and .preview.png files correctly, but now also downloads the .html file to the 'model download location'.
- The .html file saved now doesn't use the locally downloaded sample images anymore. Instead, it uses the images hosted on image.civitai.com. In my opinion this is a very bad change, since the images would no longer be viewable in case the files are no longer available on civitai, going against the archival aspect of saving the samples info with the .html file.

**With both new options _ENABLED_ and a custom image save location set:**

- 'Save model info' still with same error.
- 'Save images' still download sample images to the custom location correctly but does not save the .html and .civitai.info file to the custom location.
- 'Save images' again downloads the .preview.png file in the 'model download location' when it shouldn't.
- 'Download model' correctly downloads the .safetensors, .json and .preview.png files, but again, also downloads the .html file to the 'model download location'.
- 'Download model' now automatically downloads the .api_info.json file (old .civitai.info?) and all sample images, but it does so to the download location, ignoring the custom image save location completely.

### Expected behavior

The expected behaviour:

- **'Save model info'** used to save the **.json** file to the 'Download folder' selected. My suggestion is to save the new **.api_info.json** (old .civitai.info) file instead, since the **.json** file is already downloaded together with the model file anyways. In the case of my suggestion, **.api_info.json** should be save in the 'Download folder' selected OR in the **'custom image save location'** if that is configured in the settings.
- **'Save images'** should save **all sample images** and the **.html file** with the sample prompts to the 'Download folder' selected. If there is a **'custom image save location'** set in the settings, however, it should download both to that location.
- **'Save images'** should NOT save the **.preview.png** file to the 'Download folder'. That already happens when downloading the model (and the sample images already include the image used as .preview.png).
- **'Download model'** should download the **model** file (.safetensors), the **.json** and the **.preview.png** files to the 'Download folder'.
- If the new **'auto save info after download'** option is enabled, after downloading the model, the same behaviour as pressing the 'Save model info' should occur afterwards: save the .api_info.json file to the 'Download folder' selected **OR to the 'custom image save location' if set.**
- If the new **'auto save images after download'** option is enabled, after download the model, the same behaviour as pressing the 'Save images' should occur afterwards: save all sample images and the .html file to the 'Download folder' selected **OR to the 'custom image save location' if set.**

### System info

* Extension version: 177ce5d1
* OS: Win11
* SD-WebUI version: 1.7.0
* Python: 3.10.6

### Console logs

```Shell
Traceback (most recent call last):
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "H:\SDWebui\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 468, in save_model_info
    result = find_and_save(api_response, sha256, file_name, json_file, False, overwrite_toggle)
  File "H:\SDWebui\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 493, in find_and_save
    for item in api_response.get('items', []):
AttributeError: 'NoneType' object has no attribute 'get'
```

### Additional information

I think it is very important for the .html files to use the sample images saved locally instead of linking the images from civitai, specially since they are (were) downloaded together and to the same folder. This was a very useful function for archival purposes. Since many models, or specific versions of models, end up removed by their original uploaders and their info lost, always having that copy available locally and offline is a big positive.

**Comment by BlafKing** [comment] 2024-02-09 06:54
Thanks for reporting.

Many of the things you listed actually aren't bugs, but intended behavior with the new HTML preview page when clicking a models CivitAI icon in txt2img and img2img.

I'll go over your points:

> `Save model info` does not work and gives an error message

Thanks for the logs, I'll make sure to fix this in the upcoming update.

‎
> 'Save images' downloads sample images correctly but no longer saves the .html file and .civitai.info (now renamed to .api_info.json?)

That's correct, these files are now saved when the `Save model info` option is used instead, since, well, they aren't images, and I found it confusing that these downloads were listed under the images option.
The civitai.info is also indeed renamed, since it was an arbitrary filetype before, while it's actually just a `.json` file, this is done to avoid any confusion with the file type.

‎
> 'Save images' now downloads the .preview.png file to the 'model download location' ahead of time.

This is done since the Save Images function is now also used to save the preview images when the `Automatically save all images` option is turned on, I wanted to avoid saving the same file twice, being as a preview image and as a one of the model images, but I understand that this may not be the desired behavior.
I'll change this back to the old behavior, where the save images function saves the preview image as `model_name_0.png`

‎
> 'Download model' continues saving the .safetensors, .json and .preview.png files correctly, but now also downloads the .html file to the 'model download location'.

This is intended behavior, this is done for the new HTML preview, when clicking a model card's CivitAI button, if the option `Use local HTML file for model info` is used, then the extension needs to be able to find the HTML file matching the model, which is why it's now located in the same directory as the model.

‎
> The .html file saved now doesn't use the locally downloaded sample images anymore. Instead, it uses the images hosted on image.civitai.com

This is done since not every user will save all the images of a model, and when the `Use local HTML file for model info` is turned on, then the .html file will be used in the model info pop up when clicking the CivitAI button on model cards, and it needs to be able to display the images there, which is why local pathing is not used.

Furthermore, the local pathing to images cannot be used in the pop up window since it gets created in Javascript, which does not have local file access, and can thus not display these images if they reference a local path on the PC:
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/65f90ca3-8549-4875-aba1-6969c081a520)

I'll add two new options:
One so that you can toggle using local paths in the HTML, but do note that this will make those HTML files not longer work when the `Use local HTML file for model info` is used.

And the other option can be used to save the HTML and api_info file into the custom images location.

**Comment by BlafKing** [comment] 2024-02-09 15:40
I've now published a new update with the changes I've mentioned,

I'll go ahead and close this bug report since the issues should be fixed, thanks again for reporting!

**Closed by BlafKing** 2024-02-09 15:40 UTC
Labels: bug, WIP

**Comment by hakaserver** [comment] 2024-02-09 20:11
That was fast! 😮
I suspected some of what I reported was intended changes, but since I was not entirely sure I reported based on the behaviour from the previous commit. Thanks for the quick fix and specially thanks for including the options you mentioned! It does make sense the new changes for where to save each file, but I'll use the option to continue saving them separately to my info backup folder! 😊👍
