### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SpydirRoot** [BlafKing/sd-civitai-browser-plus#47] opened 2023-09-27 21:01 UTC
**Bug (Assuming it is a bug?)**
Textual Inversions to not download - new or updated. 

**To Reproduce**

1. Go to 'Browser Tab'
2. Search for any Textual Inversion
3. Select Download
4. Status says downloaded:
<img width="749" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/146275462/3e46c430-374f-46a2-a610-4d8b5cfbb680">

5. No .pt file downloaded.  Only files downloaded:
/{TI_Name}.json
/{TI_Name}.preview.png
/{TI_Name}/version **//No Extension**
/{TI_Name}/data.kpl
/{TI_Name}/data/0 **//No Extension**
<img width="567" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/146275462/647ea6fa-5112-4958-8a49-0a664c08e40c">

.

**Expected behavior**
Expecting a "{TI_Name}.pt" to be downloaded.  Downloading of LoRa etc., is working as expected.

**Additional context**
* Extension version: [30c15754](https://github.com/BlafKing/sd-civitai-browser-plus/commit/30c157547004e1daf54bb02b38c95e36f24140f2)
* OS: OS (Windows)
* SD version: [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
* Python: 3.10.9
* Love your work and efforts.  Just discovered your extension yesterday, and very impressed.

**Comment by BlafKing** [comment] 2023-09-27 22:53
Thanks for letting me know!
It looks like this was caused by the new automatically unpack .zip files function in the settings, when turned on, it checked if the downloaded file is an archive, not just a .zip, since a '.pt' file is an archive it unpacked it and then removed the original .pt fie.

I've changed the code so that it now checks if the downloaded file ends with '.zip' instead of checking if it is an archive.
This causes the .pt files to no longer be unpacked when the option is turned on!

I'll close this thread since the error should now be fixed in v1.12.4 :)

**Closed by BlafKing** 2023-09-27 22:53 UTC
