### ISSUE TITLE
[Bug]:  Failed to Resolve Hostname (Delivery Workers)  -> throwing unknown ARIA2 error

### ISSUE THREAD

**Issue by Volv1t3** [BlafKing/sd-civitai-browser-plus#216] opened 2024-02-26 01:38 UTC
### Describe the bug.

The bug happens when trying to download single or batch models form the extension. When models are selected the extension works fine, the issue arises when sending them to download, they might show up on the queue but the download bar does not update. In other instances it can throw an error directly.

Error Log after trying to download one model PhotoAsian:

```
02/25 20:27:35 [ERROR] CUID#10 - Download aborted. URI=https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/model/2515131/photoasianv2.aL6R.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22photoAsian_v20.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20240226/us-east-1/s3/aws4_request&X-Amz-Date=20240226T012728Z&X-Amz-SignedHeaders=host&X-Amz-Signature=db3f920e4fc6c053092fdd5f1f23c29dc006395bdb1d46ade276a041b9c6ea30
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/model/2515131/photoasianv2.aL6R.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22photoAsian_v20.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20240226/us-east-1/s3/aws4_request&X-Amz-Date=20240226T012728Z&X-Amz-SignedHeaders=host&X-Amz-Signature=db3f920e4fc6c053092fdd5f1f23c29dc006395bdb1d46ade276a041b9c6ea30
  -> [NameResolver.cc:58] errorCode=19 Failed to resolve the hostname civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com, cause: Unknown error

02/25 20:27:35 [NOTICE] Download GID#7410d47051cf20dc not complete: C:/Users/santi/AppData/Roaming/StabilityMatrix/Packages/Stable Diffusion Web UI/models/Stable-diffusion/photoAsian_v20.safetensors
CivitAI Browser+: Error occured during download of "photoAsian_v20.safetensors"
```

This happens both with and without ARIA2. In the case of downloads without ARIA2 it reports that the CIVITAI API is not responding and attempts two times to reconnect before failing.

### Steps to reproduce the problem.

1. Open the application and search for any model or filter the search for a set of models
2. Select model/s to download and press download all selected / download
3. Error will be raised in this instant, showing up in the console log for the application.

### Expected behavior

The models should be downloaded, with out without ARIA2 into my pc. Inside the designated folder. With their respective JSON information and preview.

### System info

* Extension version: 3.4.1 Commit version is set to [bcf6c187](https://github.com/BlafKing/sd-civitai-browser-plus/commit/bcf6c1872b8df05d359142bd87cb28fafdb3f9a7) and it is not updatable through webui
* OS: Windows 11 Pro
* SD-WebUI version: 1.7.0
* Python: 3.10.11

### Console logs

```Shell
The issue is raised every time there is a download in progress and this happens for any model I attempt to download. The entire console output is the following:


venv "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0
Commit hash: d500e58a65d99bfaa9c7bb0da6c3eb5704fadf25
C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-webui-controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --use-directml --opt-sub-quad-attention --opt-split-attention-v1 --upcast-sampling --no-half --lowvram
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\styles.csv
[-] ADetailer initialized. version: 24.1.2, num models: 9
CivitAI Browser+: Aria2 RPC started

02/25 20:26:30 [NOTICE] IPv4 RPC: listening on TCP port 24000

02/25 20:26:30 [NOTICE] IPv6 RPC: listening on TCP port 24000
fatal: No names found, cannot describe anything.
Using sqlite file: C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
ControlNet preprocessor location: C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-webui-controlnet\annotator\downloads
2024-02-25 20:26:32,128 - ControlNet - INFO - ControlNet v1.1.440
2024-02-25 20:26:32,408 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [6fa438a7af] from C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\models\Stable-diffusion\Stable-diffusion\amIReal_V43.safetensors
2024-02-25 20:26:33,513 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 24.9s (prepare environment: 3.6s, import torch: 5.7s, import gradio: 2.0s, setup paths: 1.5s, initialize shared: 1.6s, other imports: 0.8s, setup codeformer: 0.1s, list SD models: 0.4s, load scripts: 6.0s, create ui: 2.1s, gradio launch: 0.6s, app_started_callback: 0.5s).
Loading VAE weights specified in settings: C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\models\VAE\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sub-quadratic... done.
Model loaded in 6.9s (load weights from disk: 1.6s, create model: 0.7s, apply weights to model: 2.0s, apply float(): 1.1s, load VAE: 0.5s, calculate empty prompt: 0.9s).
Traceback (most recent call last):
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 226, in download_start
    model_item = create_model_item(dl_url, model_filename, install_path, model_name, version_name, model_sha256, model_id, create_json)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 110, in create_model_item
    for item in gl.json_data['items']:
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 426, in update_models_dropdown
    model_versions = _api.update_model_versions(model_id)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 569, in update_model_versions
    for item in api_json['items']:
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 426, in update_models_dropdown
    model_versions = _api.update_model_versions(model_id)
  File "C:\Users\santi\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion Web UI\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 569, in update_model_versions
    for item in api_json['items']:
TypeError: 'NoneType' object is not subscriptable

02/25 20:27:35 [ERROR] CUID#10 - Download aborted. URI=https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/model/2515131/photoasianv2.aL6R.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22photoAsian_v20.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20240226/us-east-1/s3/aws4_request&X-Amz-Date=20240226T012728Z&X-Amz-SignedHeaders=host&X-Amz-Signature=db3f920e4fc6c053092fdd5f1f23c29dc006395bdb1d46ade276a041b9c6ea30
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/model/2515131/photoasianv2.aL6R.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22photoAsian_v20.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20240226/us-east-1/s3/aws4_request&X-Amz-Date=20240226T012728Z&X-Amz-SignedHeaders=host&X-Amz-Signature=db3f920e4fc6c053092fdd5f1f23c29dc006395bdb1d46ade276a041b9c6ea30
  -> [NameResolver.cc:58] errorCode=19 Failed to resolve the hostname civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com, cause: Unknown error

02/25 20:27:35 [NOTICE] Download GID#7410d47051cf20dc not complete: C:/Users/santi/AppData/Roaming/StabilityMatrix/Packages/Stable Diffusion Web UI/models/Stable-diffusion/photoAsian_v20.safetensors
CivitAI Browser+: Error occured during download of "photoAsian_v20.safetensors"
```
```


### Additional information

_No response_

**Comment by BlafKing** [comment] 2024-03-11 00:17
Thanks for reporting!

Unfortunately it looks like this is not something that can be fixed from within the extension.

The error indicates a DNS resolution failure, which means your system is unable to locate the server needed to download the file.
This problem is often due to network or DNS configuration issues, which are unfortunately outside the scope of the application's control.
A few things you can try are:

* Try to use a VPN to check if the issue is region-specific.
* Change your DNS servers to Google DNS (8.8.8.8, 8.8.4.4) or Cloudflare DNS (1.1.1.1).
* Flush your DNS cache. (You can find instructions online on how to do so)

I'll close this bug report, as it's not an issue with the extension itself, feel free to send another message here if you need more help though, it's not something that I can directly fix but I can always try to suggest solutions :)

**Closed by BlafKing** 2024-03-11 00:17 UTC
Labels: bug
