### ISSUE TITLE
[BUG] Unable to download model with libaria2.so error

### ISSUE THREAD

**Issue by jaron-l** [BlafKing/sd-civitai-browser-plus#18] opened 2023-09-08 18:35 UTC
**Describe the bug**
Not entirely sure what you want to do with this but I thought I'd write it up in case it helps someone else. Feel free to close this if you think this is not needing support or if you find a way to bundle aria2 with the package.

With your recent update in v1.9, you added aria2 as the way to download models. Unfortunately, this requires a dynamic library that is not always present in systems, probably more particularly instances that are in trimmed down docker containers. This will result in the following error when trying to download a model that shows in the logs.

```
aria2c failed with error: /opt/stable-diffusion/02-sd-webui/webui/extensions/sd-civitai-browser-plus/aria2/aria2c: error while loading shared libraries: libaria2.so.0: cannot open shared object file: No such file or directory
```

A quick fix is to install aria2 from your package manager.

**To Reproduce**
1. Go to any model
2. Download that model
3. Observe timeout in webui
4. See error in logs as described above

**Expected behavior**
Models to download

**Additional context**
- Used commit ce7d6cbd826736c349bf4e4d7c5068bda4bcedc9 to get around issue without downloading aria2 but then could use v1.9 when I installed aria2
- automatic 1111 version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  
- python: 3.10.12  -
-  torch: 2.0.1+cu118  
- xformers: 0.0.20  
- gradio: 3.41.2  
- checkpoint: [879db523c3]

**Comment by BlafKing** [comment] 2023-09-08 19:25
Thank you for letting me know that aria2 doesn't work by default for you, I assume you're using Linux?
(The missing package `libaria2.so.0` is only for Linux so I pretty much know for sure but I'd just like to double check)

afaik, it should bundle the required package(s) for windows installations but I didn't get it to work properly with Linux yet, completely forgot to add a little install note for Linux users, for now I'll go and add that to the main page and I'll definitely look into finding a way to properly bundle aria2 with the package on Linux.

**Comment by saltyollpheist** [comment] 2023-09-08 21:23
Appreciate the attempted triage, @BlafKing, and maybe this is due to my error, but I'm still unable to get it working after installing aria2 as instructed on your main page. I restarted _webui.sh_ after installation, but error still persists. Do I need to restart my system entirely after installing the package? 

If it helps my system is AlmaLinux 9.2. Let me know if any other information needs to be provided and I'll happily supply it. Many thanks.

**Comment by BlafKing** [comment] 2023-09-08 21:28
I'll have a look into troubleshooting the issue, thanks for the info! @saltyollpheist 
Do you receive the same error as @jaron-l posted?

**Comment by BlafKing** [comment] 2023-09-08 22:03
I've inserted the old download method again if aria2 returns an error, it should work as far as I can tell but I'm not able to test code for Linux well so please do let me know if the work around works for now!
I'll start to troubleshoot the aria2 implementation on Linux now

**Comment by alex-red** [comment] 2023-09-09 23:35
Chiming in here to say that I see the same issue with a different missing lib, also running inside a docker container:
```shell
aria2c failed with error: /data/config/auto/extensions/sd-civitai-browser-plus/aria2/aria2c: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /data/config/auto/extensions/sd-civitai-browser-plus/aria2/aria2c
```

Your fallback works, but seems like the `stat` call is failing now for tracking the progress. Not a big deal though.
```shell
webui-docker-auto-1  | Exception in thread Thread-11 (download_file_old):
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
webui-docker-auto-1  |     self.run()
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
webui-docker-auto-1  |     self._target(*self._args, **self._kwargs)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai-api.py", line 207, in download_file_old
webui-docker-auto-1  |     save_preview_image(preview_html, file_path, install_path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai-api.py", line 948, in save_preview_image
webui-docker-auto-1  |     if not os.path.exists(install_path):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/genericpath.py", line 19, in exists
webui-docker-auto-1  |     os.stat(path)
webui-docker-auto-1  | TypeError: stat: path should be string, bytes, os.PathLike or integer, not Progress
```

Thanks for this extension by the way :) really helpful

**Comment by BlafKing** [comment] 2023-09-10 15:47
Thanks for the heads up @alex-red!

the stat error was caused by a silly oversight of me, it was an easy fix and I've published a quick hotfix for it.

**Comment by BlafKing** [comment] 2023-09-10 15:54
## To Linux users: 
It looks like Aria2 cannot be properly shipped with this extension.
You'll have to install Aria2 manually if you'd like to use Aria2 for downloading.
The extension will now automatically properly uses the old download function again if Aria2 has not been installed or if it failed to load.

I'll close this thread since afaik any issues should now be caused by Aria2 not properly working on your Linux distro.
Thanks for sharing all the error logs and descriptions everyone! ❤️

**Closed by BlafKing** 2023-09-10 15:54 UTC
Labels: bug
