### ISSUE TITLE
Download button disappeared after deleting model

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#6] opened 2023-08-29 15:29 UTC
I downloaded a textual inversion. The download showed successful, but the model was 0 kb in the folder, so the extension detected it as installed.

I used the Delete Model button to delete it. The Download Model button disappeared after that, and would not come back even after refreshing the UI. I tried to reload UI, but my auto1111 gave errors and wouldn't reload... not sure if that was related. Restarting auto1111 resolved the issue.

So this may be an isolated incident, but wanted to bring it to your attention. The other issue mentioned above is the download actually failed since it was not the right file size, but was detected as installed anyway. I've seen files partially downloaded many times with other extensions such as Civitai Helper, so that seems to be an issue with the Civitai API itself (or maybe even Gradio).

You may want to consider adding size matching locally to the size on server when detecting installed models, and if they don't match, have a "redownload" option or something like that.

**Comment by Vetrov0x** [comment] 2023-08-29 21:13
Same

**Comment by BlafKing** [comment] 2023-08-29 22:16
I'll start troubleshooting, thx for bringing it to my attention, there is already code implemented which checks if the total file size is what's being expected from CivitAI, so it does look like the issue is caused by CivitAI like you mentioned.
It checks the file size to see if the download is completed so it must be breaking elsewhere, the current way in which buttons get re-enabled is a bit messy, so cleaning up that code should resolve most of the issues you're experiencing!
I'll start working on that tomorrow along with all the other requested features! :)

**Comment by BlafKing** [comment] 2023-08-30 02:16
I've published a quick hotfix to help these issues, I wasn't able to recreate any of the issues mentioned in this post, but I've added extra checks for file size after saving, and I've force updated the Download button to re-appear after function completion.

Although it may seem simple, Introducing an extra re-download button or renaming the download button when a download has failed would be quite a hassle to implement, so unfortunately you'll just have to check if the downloaded version has an [installed] tag after downloading to make sure it has successfully downloaded, since the code will now make sure to remove any downloads that aren't of the proper size.

I'll close this thread since these errors should now be fixed, but please do send a reply here if the error occurs again, I'll then look into it again!

(Other feature requests will be implemented tomorrow😄)

**Comment by BlafKing** [comment] 2023-08-30 02:16
I've published a quick hotfix to help these issues, I wasn't able to recreate any of the issues mentioned in this post, but I've added extra checks for file size after saving, and I've force updated the Download button to re-appear after function completion.

Although it may seem simple, Introducing an extra re-download button or renaming the download button when a download has failed would be quite a hassle to implement, so unfortunately you'll just have to check if the downloaded version has an [installed] tag after downloading to make sure it has successfully downloaded, since the code will now make sure to remove any downloads that aren't of the proper size.

I'll close this thread since these errors should now be fixed, but please do send a reply here if the error occurs again, I'll then look into it again!

(Other feature requests will be implemented tomorrow😄)

**Closed by BlafKing** 2023-08-30 02:16 UTC

**Comment by BlafKing** [comment] 2023-08-30 02:18
I've published a quick hotfix to help these issues, I wasn't able to recreate any of the issues mentioned in this post, but I've added extra checks for file size after saving, and I've force updated the Download button to re-appear after function completion.

I'll close this thread since these errors should now be fixed, but please do send a reply here if the error occurs again, I'll then look into it again!

(Other feature requests will be implemented tomorrow😄)

**Comment by BlafKing** [comment] 2023-08-30 02:31
I've published a quick hotfix to help these issues, I wasn't able to recreate any of the issues mentioned in this post, but I've added extra checks for file size after saving, and I've force updated the Download button to re-appear after function completion.

It's unfortunately not feasible to verify a proper install by comparing local file size to server size, since this would require an individual API request for every detected file which isn't really feasible considering the load time that this would create if many tiles on a page are installed.

It could be possible to do this each time you click a tile, but it's easier to just make sure no broken files get saved.
The extension now makes sure that no broken files get saved by checking the file size after the file has been saved and if there's a mismatch, the file will get removed.

I'll close this thread since these errors should now be fixed, but please do send a reply here if the error occurs again, I'll then look into it again!

(Other feature requests will be implemented tomorrow😄)
