### ISSUE TITLE
Feature Request(s) - Base Model Selection

### ISSUE THREAD

**Issue by mccabedd** [BlafKing/sd-civitai-browser-plus#1] opened 2023-08-26 13:45 UTC
Why this extension isn't incorporated into A1111 is beyond me. Thank you for an amazing job!

I do have possible update ideas though.

- 1) The ability to filter out Base Models. That is, (for example) view or search for only 1.5 models. Maybe even limit the filter choice to only 1.5, 2.0, 2.1 & SDXL1.0

- 2) Models currently all point to, and are saved to their default folder (example: path/to/sd/model/lora)

 Nested folders don't seem to be detected: (path/to/sd/model/lora/clothing  or  path/to/sd/model/lora/hairstyles)

- 3) Saved State. I don't know if this is just me, but upon every launch, the previous state reverts to default values. (Checkboxes, Tile Count, etc...)

- 4) More of a nice to have really, but the ability to adjust the Tile size would be delicious!! 

Again, thank you for the incredible work on this extension, and I look forward to seeing how it evolves in the future.

**Comment by BlafKing** [comment] 2023-08-26 15:09
Thanks for the kinds words and feature requests! I appreciate you taking the time to write in!  
About your requests:
* 1. Unfortunately as of right now, it's not possible to filter on Base Models since the Civit API does not yet support this.  
I will however make sure to add Base Model filtering as soon as the Civit API supports this!
‎ 
* 2. I haven't thought about models being undetected when nested, thanks for pointing that out! I'll try to find a fitting solution so that models get detected even when they are nested!
‎ 
* 3. You can currently change the default settings which get used upon launch inside `path/to/sd/webui/ui-config.json`  
I'll have a look to see if I can make it so that main settings get automatically saved to that file!
‎ 
* 4. Another good request, I agree! I'll try implementing this in an upcoming update!

**Comment by SaturnFXS** [comment] 2023-08-27 16:40
> Thanks for the kinds words and feature requests! I appreciate you taking the time to write in! About your requests:
> 
> * 1. Unfortunately as of right now, it's not possible to filter on Base Models since the Civit API does not yet support this.
>      I've submitted a feature request for the API and will make sure to add Base Model filtering as soon as the Civit API supports this!
>      ‎
> * 2. I haven't thought about models being undetected when nested, thanks for pointing that out! I'll try to find a fitting solution so that models get detected even when they are nested!
>      ‎
> * 3. You can currently change the default settings which get used upon launch inside `path/to/sd/webui/ui-config.json`
>      I'll have a look to see if I can make it so that main settings get automatically saved to that file!
>      ‎
> * 4. Another good request, I agree! I'll try implementing this in an upcoming update!

Would it be hard to have a pulldown that separates based on nested directory? I have my models, loras, etc each in their own directory based on things like versions, styles, etc in my loras and sdmodels and just being able to choose based on which I am searching which subdirectory to read only would be extremely helpful (or just choose the base directory for all models if I am a madman)

**Comment by BlafKing** [comment] 2023-08-27 20:23
> Would it be hard to have a pulldown that separates based on nested directory? I have my models, loras, etc each in their own directory based on things like versions, styles, etc in my loras and sdmodels and just being able to choose based on which I am searching which subdirectory to read only would be extremely helpful (or just choose the base directory for all models if I am a madman)

I'm not exactly sure if I understand you're request, are you asking for a dropdown box to define which folder to save a download to?  

Or a dropdown to filter search results based on a selected nested directory?

**Comment by ManOrMonster** [comment] 2023-08-27 20:51
> * 1. Unfortunately as of right now, it's not possible to filter on Base Models since the Civit API does not yet support this.
>      I've submitted a feature request for the API and will make sure to add Base Model filtering as soon as the Civit API supports this!

You already know this, but the base model is returned for each entry. Add a filter that allows selecting one or more base models and then those are simply hidden from the entries that are returned (which would include all base models). You could even make it so that filters could be added/removed after results and they would show or hide dynamically without extra API calls. This method might even work faster than Civitai's web page when changing base model selections.

‎
> * 2. I haven't thought about models being undetected when nested, thanks for pointing that out! I'll try to find a fitting solution so that models get detected even when they are nested!

This would be amazing. Once you implement this, it would be great to implement something similar to what SaturnFXS mentioned above... have a select that contains all subfolders, which would allow choosing the target download folder (like [Civitai Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper) currently does, example below),

<img width="297" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/a0ed793f-579b-433e-a698-224e50e1f29e">

‎
> * 3. You can currently change the default settings which get used upon launch inside `path/to/sd/webui/ui-config.json`
>      I'll have a look to see if I can make it so that main settings get automatically saved to that file!

Easiest way to do this is to change the options you'd like as default, then in Settings, click on "Defaults" on the left, then "View Changes", then "Apply" if you are satisfied. This works for most inputs in Auto1111, including extensions.

**Comment by BlafKing** [comment] 2023-08-27 22:10
> You already know this, but the base model is returned for each entry. Add a filter that allows selecting one or more base models and then those are simply hidden from the entries that are returned (which would include all base models). You could even make it so that filters could be added/removed after results and they would show or hide dynamically without extra API calls. This method might even work faster than Civitai's web page when changing base model selections.

Due to how the script is currently made, it's not really easy to filter results after they've been inserted into the HTML section by the API request. I'm sure it's possible but I'll wait for a response from the CivitAI team to see if Base Model filtering will be implemented anytime soon otherwise I'll start looking for other solutions, I didn't think about this option yet though so thanks for pointing it out!

> This would be amazing. Once you implement this, it would be great to implement something similar to what SaturnFXS mentioned above... have a select that contains all subfolders, which would allow choosing the target download folder (like [Civitai Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper) currently does, example below),

I didn't really understand SaturnFXS request but I see the intention now! I've currently implemented a textbox in which you can fill in the final folder location by hand, but I like this solution a lot more and it feels a lot cleaner, I'll start implementing that!

> Easiest way to do this is to change the options you'd like as default, then in Settings, click on "Defaults" on the left, then "View Changes", then "Apply" if you are satisfied. This works for most inputs in Auto1111, including extensions.

I wasn't aware that there is a Default tab, that seems like a very easy solution! I already wrote some code that saves the settings anytime you change something but I can foresee some people disliking this so I'll go and comment that out.

**Comment by ManOrMonster** [comment] 2023-08-27 22:28
> Due to how the script is currently made, it's not really easy to filter results after they've been inserted into the HTML section by the API request. I'm sure it's possible but I'll wait for a response from the CivitAI team to see if Base Model filtering will be implemented anytime soon otherwise I'll start looking for other solutions, I didn't think about this option yet though so thanks for pointing it out!

Add `data-base-model="{item['baseModel']}"` attribute to each `figure` element, then dynamically `display: none` for each baseModel not selected. Not sure it would be that easy, but just another idea. You could even make the filter only display base models that were returned to simplify things for the user.

Or you could just add it to the class  like you do with `{nsfw}` and `{installstatus}`.

`
HTML = HTML + f'<figure class="civmodelcard {nsfw} {installstatus}" data-base-model="{item['baseModel']}" onclick="select_model(\'{model_name}\')">' 
`

Also, thanks for this extension. I've been waiting for something simple like this to streamline downloading from Civitai.

**Comment by BlafKing** [comment] 2023-08-27 22:36
Thanks for the suggestions! Seems reasonable to implement it that way, I was thinking way too complicated :,)
I'll try to implement the Base Model filtering, I've almost finished all the other additions so expect an update somewhere today 👍🏻

And no worries! Glad I can help out to make the experience less of a hassle! :)

**Comment by BlafKing** [comment] 2023-08-28 02:23
All features have been implemented except for Base Model filtering for now.

I spent too much time fixing bugs caused by adding the other new features to my spaghetti code, so I'll try to tackle Base Model filtering tomorrow after some good sleep 😴

**Comment by ManOrMonster** [comment] 2023-08-28 03:51
Super solid update! Well done. As far as I'm concerned, this is almost complete.

One issue is that when I choose LoCon content type, it points to the "Lycoris" folder.  However, I no longer have a Lycoris folder after Auto1111 1.5, since it treats LORAs and LoCons the same now. I store both together in the Lora folder.

I've fixed it for myself for now by editing civitai-api.py (code below). I know I should be able to update the default somewhere but I am unable to figure out where.

```
elif content_type == "LoCon":
        # if "lyco_dir" in cmd_opts:
        #     folder = f"{cmd_opts.lyco_dir}"
        # elif "lyco_dir_backcompat" in cmd_opts:
        #     folder = f"{cmd_opts.lyco_dir_backcompat}"
        # else:
            folder = os.path.join(models_path,"Lora")
```

**Comment by BlafKing** [comment] 2023-08-28 11:40
> One issue is that when I choose LoCon content type, it points to the "Lycoris" folder. However, I no longer have a Lycoris folder after Auto1111 1.5, since it treats LORAs and LoCons the same now. I store both together in the Lora folder.

Good catch! I'll add a check that uses the LORA folder based on the version of A1111 that is being used.

**Comment by BlafKing** [comment] 2023-08-28 14:47
The latest version now includes automatically saving LoCon to the Lora folder if A1111 is v1.5 or higher.
I've also included a dropdown box which can be used to hide any unselected Base Models. 
I'll replace this dropbox with one that can influence search results once the API supports it, since the current implementation can result in pages being empty and it's overal not a great solution imo.

Thanks for all the suggestions and kind words to everyone who submitted requests/explinations, I'll close this thread now but feel free to open another one if anyone else has issues/requests/ideas!

**Closed by BlafKing** 2023-08-28 14:47 UTC
